//NOTES
// approx 20 seconds is ALWAYS and setup shenanigans before beginning this code
// v3.2.0:  39.57 seconds
// revised: 26.43 seconds

COPY_EXISTING_REGEXP ~^.+\.cre$~ ~override~
  READ_BYTE 0x8a totallevel
  PATCH_IF ((totallevel > 0) AND (totallevel < 31)) BEGIN
    WRITE_BYTE 0x25a totallevel
  END
  BUT_ONLY  

COPY_EXISTING ~63glabs1.cre~ ~override~ 
              ~63glabsl.cre~ ~override~ 
              ~63glabsr.cre~ ~override~
	WRITE_BYTE 0x25a 0
  BUT_ONLY 