// Bubb Notes - WRITE_ASCII writes the literal bytes that are imbedded in the given string, it doesn't matter if they aren't visible characters.
// I have used WRITE_ASCII to write large groups of bytes at once. I had to hex-edit the bytes into this file;
// DO NOT ATTEMPT TO EDIT THE WRITE_ASCII VALUES WITH A CONVENTIONAL TEXT EDITOR!

COPY ~IWD2.exe~ ~IWD2.exe~

	WRITE_ASCII 0x31DB38 ~ép~
	WRITE_ASCII 0x31DB67 ~éˆ~
	WRITE_ASCII 0x446AAD ~‹¾ú~
	WRITE_ASCII 0x446AB3 ~;ût‹Ïè…¼ÿWèÀ^ûÿƒÄ‰ú~
	WRITE_ASCII 0x446ACD ~‹D$\‰†ú~
	WRITE_ASCII 0x446AD7 ~‹‹PÆP~
	WRITE_ASCII 0x446AE2 ~‰L$‰T$VL$éØqíÿPQRW‹¾ş~
	WRITE_ASCII 0x446AFE ~;ût‹Ïè·„¼ÿWèu^ûÿƒÄ‰ş~
	WRITE_ASCII 0x446B18 ~‹D$l‰†ş~
	WRITE_ASCII 0x446B22 ~‹‹P‹T$4‰–üO~
	WRITE_ASCII 0x446B31 ~‹D$8‰†~
	WRITE_ASCII 0x446B38 ~P~
	WRITE_ASCII 0x446B3B ~_ZYX‰ş~
	WRITE_ASCII 0x446B45 ~‹D$\‰†ş~
	WRITE_ASCII 0x446B4F ~‹‹PÆH~
	WRITE_ASCII 0x446B5A ~‰L$‰T$VL$é`qíÿ~

IF_EXISTS
