//NOTES
//COPY ~%mod_folder%/are/AR6103.are~ ~override~

// patches a door so you can force it open and also rigs the northmost exit in Lord Pyros' domain to lead to the Fields of Slaughter instead of back to Dragon's Eye

COPY_EXISTING ~AR6103.are~ ~override~
 WRITE_BYTE 0xE428 99
BUT_ONLY
COPY_EXISTING ~AR6104.are~ ~override~
 WRITE_BYTE 0x91E6 0x36
 WRITE_BYTE 0x91E7 0x32
 WRITE_BYTE 0x91E8 0x30
 WRITE_BYTE 0x91E9 0x30
BUT_ONLY