//NOTES
//We should patch these
// replaces items that grant immunities to common enemy types and bosses

COPY ~%mod_folder%/itm/BOSSRNG1.itm~ ~override~
COPY ~%mod_folder%/itm/BOSSRNG2.itm~ ~override~
COPY ~%mod_folder%/itm/LICHRNG1.itm~ ~override~
COPY ~%mod_folder%/itm/DEMRNG1.itm~ ~override~
COPY ~%mod_folder%/itm/41ORIA.itm~ ~override~
COPY ~%mod_folder%/itm/11VEIRA3.itm~ ~override~
COPY ~%mod_folder%/itm/00CIDEAD.itm~ ~override~
COPY ~%mod_folder%/itm/00CIDED1.itm~ ~override~
