//NOTES
//


	//	v1.0
	DEFINE_PATCH_FUNCTION	IWD2_ADD_CRE_ITEM
		INT_VAR
			cq1 = 0
			cq2 = 0
			cq3 = 0
			equip = 1
			ability = 0
		STR_VAR
			mode = ~~
			item = ~~
			flags = ~~
			slot = ~~
	BEGIN
		READ_ASCII	0	sig	(8)
		PATCH_IF	~%sig%~	STRING_EQUAL	~CRE V2.2~	BEGIN
			LPF	IWD2_CRE_REINDEX	RET	slt_off	itm_off	itm_num	fx_off	END
			SET	flag = 0
			PATCH_IF	! ~%flags%~	STRING_CONTAINS_REGEXP	~identified~	BEGIN	SET	flag |= 1	END
			PATCH_IF	! ~%flags%~	STRING_CONTAINS_REGEXP	~unstealable~	BEGIN	SET	flag |= 2	END
			PATCH_IF	! ~%flags%~	STRING_CONTAINS_REGEXP	~stolen~			BEGIN	SET	flag |= 4	END
			PATCH_IF	! ~%flags%~	STRING_CONTAINS_REGEXP	~undroppable~	BEGIN	SET	flag |= 8	END
			TO_LOWER	slot
			TO_LOWER	mode
			SET	itm_add = 1
			INNER_PATCH	~%slot%~	BEGIN
				REPLACE_TEXTUALLY	~[ %TAB%%WNL%%MNL%%LNL%]+~	~ ~
				COUNT_2DA_COLS	cols
				READ_2DA_ENTRIES_NOW	~READ_ADD_CRE_ITEM~	cols
			END
			SET	wpn_slot = ~-1~	FOR	(i = 9; i < 16; i+=2)		BEGIN	READ_SHORT	(slt_off + i * 0x2)	index	PATCH_IF index = 65535	BEGIN	SET	wpn_slot = i	SET	i = 16	END	END
			SET	shd_slot = ~-1~	FOR	(i = 10; i < 17; i+=2)	BEGIN	READ_SHORT	(slt_off + i * 0x2)	index	PATCH_IF index = 65535	BEGIN	SET	shd_slot = i	SET	i = 17	END	END
			SET	inv_slot = ~-1~	FOR	(i = 25; i < 49; ++i)		BEGIN	READ_SHORT	(slt_off + i * 0x2)	index	PATCH_IF index = 65535	BEGIN	SET	inv_slot = i	SET	i = 49	END	END
			SET	qvr_slot = ~-1~	FOR	(i = 17; i < 20; ++i)		BEGIN	READ_SHORT	(slt_off + i * 0x2)	index	PATCH_IF index = 65535	BEGIN	SET	qvr_slot = i	SET	i = 20	END	END
			SET	qit_slot = ~-1~	FOR	(i = 22; i < 25; ++i)		BEGIN	READ_SHORT	(slt_off + i * 0x2)	index	PATCH_IF index = 65535	BEGIN	SET	qit_slot = i	SET	i = 25	END	END
			SET	rng_slot = ~-1~		FOR	(i = 4; i < 6; ++i)		BEGIN	READ_SHORT	(slt_off + i * 0x2)	index	PATCH_IF index = 65535	BEGIN	SET	rng_slot = i	SET	i = 6		END	END
			FOR	(i = 0; i < cols; ++i)	BEGIN
				READ_2DA_ENTRY_FORMER	~READ_ADD_CRE_ITEM~ 0 i slot
				PATCH_MATCH	~%slot%~
				WITH	~helmet~	BEGIN	SET	slot = 0		END	~armor~		BEGIN	SET	slot = 1		END	~shield~	BEGIN	SET	slot = 2		END	~gloves~	BEGIN	SET	slot = 3
					END	~lring~		BEGIN	SET	slot = 4		END	~rring~		BEGIN	SET	slot = 5		END	~amulet~	BEGIN	SET	slot = 6		END	~belt~		BEGIN	SET	slot = 7
					END	~boots~		BEGIN	SET	slot = 8		END	~ring~		BEGIN	SET	slot = 53		END	~inv~			BEGIN	SET	slot = 54		
					END	~weapon1~	BEGIN	SET	slot = 9		END	~shield1~	BEGIN	SET	slot = 10		END	~weapon2~	BEGIN	SET	slot = 11		END	~shield2~	BEGIN	SET	slot = 12
					END	~weapon3~	BEGIN	SET	slot = 13		END	~shield3~	BEGIN	SET	slot = 14		END	~weapon4~	BEGIN	SET	slot = 15		END	~shield4~	BEGIN	SET	slot = 16
					END	~quiver1~	BEGIN	SET	slot = 17		END	~quiver2~	BEGIN	SET	slot = 18		END	~quiver3~	BEGIN	SET	slot = 19		END	~quiver4~	BEGIN	SET	slot = 20
					END	~cloak~		BEGIN	SET	slot = 21		END	~qitem1~	BEGIN	SET	slot = 22		END	~qitem2~	BEGIN	SET	slot = 23		END	~qitem3~	BEGIN	SET	slot = 24
					END	~inv1~		BEGIN	SET	slot = 25		END	~inv2~		BEGIN	SET	slot = 26		END	~inv3~		BEGIN	SET	slot = 27		END	~inv4~		BEGIN	SET	slot = 28
					END	~inv5~		BEGIN	SET	slot = 29		END	~inv6~		BEGIN	SET	slot = 30		END	~inv7~		BEGIN	SET	slot = 31		END	~inv8~		BEGIN	SET	slot = 32
					END	~inv9~		BEGIN	SET	slot = 33		END	~inv10~		BEGIN	SET	slot = 34		END	~inv11~		BEGIN	SET	slot = 35		END	~inv12~		BEGIN	SET	slot = 36
					END	~inv13~		BEGIN	SET	slot = 37		END	~inv14~		BEGIN	SET	slot = 38		END	~inv15~		BEGIN	SET	slot = 39		END	~inv16~		BEGIN	SET	slot = 40
					END	~inv17~		BEGIN	SET	slot = 41		END	~inv18~		BEGIN	SET	slot = 42		END	~inv19~		BEGIN	SET	slot = 43		END	~inv20~		BEGIN	SET	slot = 44
					END	~inv21~		BEGIN	SET	slot = 45		END	~inv22~		BEGIN	SET	slot = 46		END	~inv23~		BEGIN	SET	slot = 47		END	~inv24~		BEGIN	SET	slot = 48
					END	~magic~		BEGIN	SET	slot = 49		END	~weapon~	BEGIN	SET	slot = 50		END	~quiver~	BEGIN	SET	slot = 51		END	~qitem~		BEGIN	SET	slot = 52
					END	DEFAULT	SET	slot = ~-1~
				END
				PATCH_IF	slot = ~-1~	BEGIN
					SET	i = cols
					PATCH_IF	inv_slot != ~-1~	BEGIN
						WRITE_SHORT	(slt_off + inv_slot * 0x2)	itm_num
					END
				END	ELSE	BEGIN
					PATCH_MATCH	slot
					WITH	2	WHEN shd_slot != ~-1~	BEGIN	slot = shd_slot
						END	50 WHEN wpn_slot != ~-1~	BEGIN	slot = wpn_slot
						END	51 WHEN qvr_slot != ~-1~	BEGIN	slot = qvr_slot
						END	52 WHEN qit_slot != ~-1~	BEGIN	slot = qit_slot
						END	53 WHEN rng_slot != ~-1~	BEGIN	slot = rng_slot
						END	54 WHEN inv_slot != ~-1~	BEGIN	slot = inv_slot
						END	DEFAULT
							READ_SHORT	(slt_off + slot * 0x2)	value
							PATCH_IF	value != 65535	BEGIN
								PATCH_IF	~%mode%~	STRING_EQUAL	~move~	BEGIN
									WRITE_SHORT	(slt_off + inv_slot * 0x2)	value
									SET	i = cols
								END
								PATCH_IF	~%mode%~	STRING_EQUAL	~replace~	BEGIN
									SET	i = cols
									SET	itm_num = value
									SET	itm_add = 0
								END
							END
					END
				END
			END
			PATCH_IF	slot = ~-1~	BEGIN
				PATCH_WARN	~No available inventory slots, item not added.~
			END	ELSE	BEGIN
				WRITE_SHORT	(slt_off + slot * 0x2)	itm_num
				PATCH_IF	itm_add	BEGIN
					INSERT_BYTES	(itm_off + itm_num * 0x14)	0x14
				END
				WRITE_ASCIIE	(itm_off + itm_num * 0x14)	~%item%~	#8
				WRITE_SHORT		(itm_off + itm_num * 0x14 + 0xa)	cq1
				WRITE_SHORT		(itm_off + itm_num * 0x14 + 0xc)	cq2
				WRITE_SHORT		(itm_off + itm_num * 0x14 + 0xe)	cq3
				WRITE_LONG		(itm_off + itm_num * 0x14 + 0x10)	flag
				PATCH_IF	equip	BEGIN
					PATCH_MATCH	slot
					WITH	9 11 13 15	BEGIN
							SET	index = (slot - 9) / 2
							WRITE_SHORT	(slt_off + 50 * 0x2)	index
							WRITE_SHORT	(slt_off + 51 * 0x2)	ability
						END	49	BEGIN
							WRITE_SHORT	(slt_off + 50 * 0x2)	1000
							WRITE_SHORT	(slt_off + 51 * 0x2)	ability
						END	DEFAULT
					END
				END
				WRITE_LONG	0x61a (THIS + itm_add)		//	Item count
				WRITE_LONG	0x61e	(THIS + itm_add * 0x14)	//	Effects offset
			END
		END
	END
	

	//	v1.0
	DEFINE_PATCH_FUNCTION	IWD2_REMOVE_CRE_ITEM
		STR_VAR
			item = ~~
	BEGIN
		READ_ASCII	0	sig	(8)
		PATCH_IF	~%sig%~	STRING_EQUAL	~CRE V2.2~	BEGIN
			INNER_PATCH_SAVE	item ~%item%~ BEGIN	INSERT_BYTES BUFFER_LENGTH 1	WRITE_BYTE (BUFFER_LENGTH - 1) 32	INSERT_BYTES 0 1	WRITE_BYTE	0 32	END
			TEXT_SPRINT	w ~[ %TAB%%WNL%%MNL%%LNL%]~
			LPF	IWD2_CRE_REINDEX	RET	slt_off	itm_off	itm_num	fx_off	END
			TO_UPPER	item
			SET	itm_add = 0
			PATCH_IF	~%item%~ STRING_EQUAL ~~	BEGIN
				DELETE_BYTES	itm_off	(itm_num * 0x14)
				FOR (j = 0; j < 50;	++j)	BEGIN
					WRITE_SHORT	(slt_off + j * 0x2)	~-1~
				END
				SET	itm_add -= itm_num
			END	ELSE	BEGIN
				FOR	(i = 0; i < itm_num; ++i)	BEGIN
					READ_ASCII	(itm_off + i * 0x14)	resref
					TO_UPPER resref
					PATCH_IF	! ~%item%~ STRING_CONTAINS_REGEXP ~%w%%resref%%w%~	BEGIN
						DELETE_BYTES	(itm_off + i * 0x14)	0x14
						FOR (j = 0; j < 50;	++j)	BEGIN
							READ_SHORT	(slt_off + j * 0x2)	slot
							PATCH_IF	slot > i	BEGIN
								WRITE_SHORT	(slt_off + j * 0x2) (THIS - 1)
							END
							PATCH_IF	slot = i	BEGIN
								WRITE_SHORT	(slt_off + j * 0x2)	~-1~
							END
						END
						SET	itm_add -= 1	SET	i -= 1	SET	itm_num -= 1
					END
				END
			END
			WRITE_LONG	0x61a (THIS + itm_add)		//	Item count
			WRITE_LONG	0x61e	(THIS + itm_add * 0x14)	//	Effects offset
		END
	END

	//	v1.0
	DEFINE_PATCH_FUNCTION	IWD2_CRE_REINDEX
		RET
			ba_0_off ba_0_num ba_1_off ba_1_num ba_2_off ba_2_num ba_3_off ba_3_num ba_4_off ba_4_num ba_5_off ba_5_num ba_6_off ba_6_num ba_7_off ba_7_num ba_8_off ba_8_num
			cl_0_off cl_0_num cl_1_off cl_1_num cl_2_off cl_2_num cl_3_off cl_3_num cl_4_off cl_4_num cl_5_off cl_5_num cl_6_off cl_6_num cl_7_off cl_7_num cl_8_off cl_8_num
			dr_0_off dr_0_num dr_1_off dr_1_num dr_2_off dr_2_num dr_3_off dr_3_num dr_4_off dr_4_num dr_5_off dr_5_num dr_6_off dr_6_num dr_7_off dr_7_num dr_8_off dr_8_num
			pa_0_off pa_0_num pa_1_off pa_1_num pa_2_off pa_2_num pa_3_off pa_3_num pa_4_off pa_4_num pa_5_off pa_5_num pa_6_off pa_6_num pa_7_off pa_7_num pa_8_off pa_8_num
			ra_0_off ra_0_num ra_1_off ra_1_num ra_2_off ra_2_num ra_3_off ra_3_num ra_4_off ra_4_num ra_5_off ra_5_num ra_6_off ra_6_num ra_7_off ra_7_num ra_8_off ra_8_num
			so_0_off so_0_num so_1_off so_1_num so_2_off so_2_num so_3_off so_3_num so_4_off so_4_num so_5_off so_5_num so_6_off so_6_num so_7_off so_7_num so_8_off so_8_num
			wi_0_off wi_0_num wi_1_off wi_1_num wi_2_off wi_2_num wi_3_off wi_3_num wi_4_off wi_4_num wi_5_off wi_5_num wi_6_off wi_6_num wi_7_off wi_7_num wi_8_off wi_8_num
			do_0_off do_0_num do_1_off do_1_num do_2_off do_2_num do_3_off do_3_num do_4_off do_4_num do_5_off do_5_num do_6_off do_6_num do_7_off do_7_num do_8_off do_8_num
			ab_off ab_num sng_off	sng_num	shp_off	shp_num	slt_off	itm_off	itm_num	fx_off	fx_num
	BEGIN
		FOR	(i = 0; i < 9; ++i)	BEGIN
			READ_LONG	(0x3ba + i * 4) $ba(~%i%~ ~off~)	READ_LONG	(0x4b6 + i * 4)	EVAL $ba(~%i%~ ~num~)	SET	$ba(~%i%~ ~size~)	 = ($ba(~%i%~ ~num~) * 0x10 + 8)	READ_ASCII	$ba(~%i%~ ~off~)	EVAL $ba(~%i%~)	($ba(~%i%~ ~size~))
			READ_LONG	(0x3de + i * 4) $cl(~%i%~ ~off~)	READ_LONG	(0x4da + i * 4)	EVAL $cl(~%i%~ ~num~)	SET	$cl(~%i%~ ~size~)	 = ($cl(~%i%~ ~num~) * 0x10 + 8)	READ_ASCII	$cl(~%i%~ ~off~)	EVAL $cl(~%i%~)	($cl(~%i%~ ~size~))
			READ_LONG	(0x402 + i * 4) $dr(~%i%~ ~off~)	READ_LONG	(0x4fe + i * 4)	EVAL $dr(~%i%~ ~num~)	SET	$dr(~%i%~ ~size~)	 = ($dr(~%i%~ ~num~) * 0x10 + 8)	READ_ASCII	$dr(~%i%~ ~off~)	EVAL $dr(~%i%~)	($dr(~%i%~ ~size~))
			READ_LONG	(0x426 + i * 4) $pa(~%i%~ ~off~)	READ_LONG	(0x522 + i * 4)	EVAL $pa(~%i%~ ~num~)	SET	$pa(~%i%~ ~size~)	 = ($pa(~%i%~ ~num~) * 0x10 + 8)	READ_ASCII	$pa(~%i%~ ~off~)	EVAL $pa(~%i%~)	($pa(~%i%~ ~size~))
			READ_LONG	(0x44a + i * 4)	$ra(~%i%~ ~off~)	READ_LONG	(0x546 + i * 4)	EVAL $ra(~%i%~ ~num~)	SET	$ra(~%i%~ ~size~)	 = ($ra(~%i%~ ~num~) * 0x10 + 8)	READ_ASCII	$ra(~%i%~ ~off~)	EVAL $ra(~%i%~)	($ra(~%i%~ ~size~))
			READ_LONG	(0x46e + i * 4) $so(~%i%~ ~off~)	READ_LONG	(0x56a + i * 4)	EVAL $so(~%i%~ ~num~)	SET	$so(~%i%~ ~size~)	 = ($so(~%i%~ ~num~) * 0x10 + 8)	READ_ASCII	$so(~%i%~ ~off~)	EVAL $so(~%i%~)	($so(~%i%~ ~size~))
			READ_LONG	(0x492 + i * 4) $wi(~%i%~ ~off~)	READ_LONG	(0x58e + i * 4)	EVAL $wi(~%i%~ ~num~)	SET	$wi(~%i%~ ~size~)	 = ($wi(~%i%~ ~num~) * 0x10 + 8)	READ_ASCII	$wi(~%i%~ ~off~)	EVAL $wi(~%i%~)	($wi(~%i%~ ~size~))
			READ_LONG	(0x5b2 + i * 4) $do(~%i%~ ~off~)	READ_LONG	(0x5d6 + i * 4)	EVAL $do(~%i%~ ~num~)	SET	$do(~%i%~ ~size~)	 = ($do(~%i%~ ~num~) * 0x10 + 8)	READ_ASCII	$do(~%i%~ ~off~)	EVAL $do(~%i%~)	($do(~%i%~ ~size~))
		END
		READ_LONG	0x5fa ab_off	READ_LONG	0x5fe	ab_num	SET	ab_size = (ab_num * 0x10 + 8)		READ_ASCII	ab_off	abilities	(ab_size)
		READ_LONG	0x602	sng_off	READ_LONG	0x606	sng_num	SET	sng_size = (sng_num * 0x10 + 8)	READ_ASCII	sng_off	songs	(sng_size)
		READ_LONG	0x60a	shp_off	READ_LONG	0x60e	shp_num	SET	shp_size = (shp_num * 0x10 + 8)	READ_ASCII	shp_off	shapes	(shp_size)
		READ_LONG	0x612	slt_off																															READ_ASCII	slt_off	slots	(0x68)
		READ_LONG	0x616	itm_off	READ_LONG	0x61a	itm_num	SET	itm_size = (itm_num * 0x14)			READ_ASCII	itm_off	items	(itm_size)
		READ_LONG	0x61e	fx_off	READ_LONG	0x622	fx_num	SET	fx_size = (fx_num * 0x108)			READ_ASCII	fx_off	effects	(fx_size)
		SET	offset = 0x62e
		PATCH_IF	(ba_0_off > ba_1_off) OR (ba_1_off > ba_2_off) OR (ba_2_off > ba_3_off) OR (ba_3_off > ba_4_off) OR
							(ba_4_off > ba_5_off) OR (ba_5_off > ba_6_off) OR (ba_6_off > ba_7_off) OR (ba_7_off > ba_8_off) OR (ba_8_off > cl_0_off) OR
							(cl_0_off > cl_1_off) OR (cl_1_off > cl_2_off) OR (cl_2_off > cl_3_off) OR (cl_3_off > cl_4_off) OR
							(cl_4_off > cl_5_off) OR (cl_5_off > cl_6_off) OR (cl_6_off > cl_7_off) OR (cl_7_off > cl_8_off) OR (cl_8_num > dr_0_off) OR
							(dr_0_off > dr_1_off) OR (dr_1_off > dr_2_off) OR (dr_2_off > dr_3_off) OR (dr_3_off > dr_4_off) OR
							(dr_4_off > dr_5_off) OR (dr_5_off > dr_6_off) OR (dr_6_off > dr_7_off) OR (dr_7_off > dr_8_off) OR (dr_8_num > pa_0_off) OR
							(pa_0_off > pa_1_off) OR (pa_1_off > pa_2_off) OR (pa_2_off > pa_3_off) OR (pa_3_off > pa_4_off) OR
							(pa_4_off > pa_5_off) OR (pa_5_off > pa_6_off) OR (pa_6_off > pa_7_off) OR (pa_7_off > pa_8_off) OR (pa_8_num > ra_0_off) OR
							(ra_0_off > ra_1_off) OR (ra_1_off > ra_2_off) OR (ra_2_off > ra_3_off) OR (ra_3_off > ra_4_off) OR
							(ra_4_off > ra_5_off) OR (ra_5_off > ra_6_off) OR (ra_6_off > ra_7_off) OR (ra_7_off > ra_8_off) OR (ra_8_num > ra_0_off) OR
							(so_0_off > so_1_off) OR (so_1_off > so_2_off) OR (so_2_off > so_3_off) OR (so_3_off > so_4_off) OR
							(so_4_off > so_5_off) OR (so_5_off > so_6_off) OR (so_6_off > so_7_off) OR (so_7_off > so_8_off) OR (so_8_num > so_0_off) OR
							(wi_0_off > wi_1_off) OR (wi_1_off > wi_2_off) OR (wi_2_off > wi_3_off) OR (wi_3_off > wi_4_off) OR
							(wi_4_off > wi_5_off) OR (wi_5_off > wi_6_off) OR (wi_6_off > wi_7_off) OR (wi_7_off > wi_8_off) OR (wi_8_num > wi_0_off) OR
							(do_0_off > do_1_off) OR (do_1_off > do_2_off) OR (do_2_off > do_3_off) OR (do_3_off > do_4_off) OR
							(do_4_off > do_5_off) OR (do_5_off > do_6_off) OR (do_6_off > do_7_off) OR (do_7_off > do_8_off) OR (do_8_num > ab_off) OR
							(ab_off > sng_off) OR (sng_off > shp_off) OR (shp_off > slt_off) OR (slt_off >= itm_off) OR (itm_off > fx_off) BEGIN
			SET	ba_0_off	= offset	WRITE_LONG	0x3ba	ba_0_off	WRITE_ASCIIE	ba_0_off	~%ba_0%~
			FOR	(i = 1; i < 9; ++i)	BEGIN	SET	j = i - 1	SET	$ba(~%i%~ ~off~)	= $ba(~%j%~ ~off~) + $ba(~%j%~ ~size~)	WRITE_LONG	(0x3ba + i * 4)	$ba(~%i%~ ~off~)	WRITE_ASCIIE	$ba(~%i%~ ~off~)	$ba(~%i%~)	END
			SET	cl_0_off	= ba_8_off + ba_8_size	WRITE_LONG	0x3de	cl_0_off	WRITE_ASCIIE	cl_0_off	~%cl_0%~
			FOR	(i = 1; i < 9; ++i)	BEGIN	SET	j = i - 1	SET	$cl(~%i%~ ~off~)	= $cl(~%j%~ ~off~) + $cl(~%j%~ ~size~)	WRITE_LONG	(0x3de + i * 4)	$cl(~%i%~ ~off~)	WRITE_ASCIIE	$cl(~%i%~ ~off~)	$cl(~%i%~)	END
			SET	dr_0_off	= cl_8_off + cl_8_size	WRITE_LONG	0x402	dr_0_off	WRITE_ASCIIE	dr_0_off	~%dr_0%~
			FOR	(i = 1; i < 9; ++i)	BEGIN	SET	j = i - 1	SET	$dr(~%i%~ ~off~)	= $dr(~%j%~ ~off~) + $dr(~%j%~ ~size~)	WRITE_LONG	(0x402 + i * 4)	$dr(~%i%~ ~off~)	WRITE_ASCIIE	$dr(~%i%~ ~off~)	$dr(~%i%~)	END
			SET	pa_0_off	= dr_8_off + dr_8_size	WRITE_LONG	0x426	pa_0_off	WRITE_ASCIIE	pa_0_off	~%pa_0%~
			FOR	(i = 1; i < 9; ++i)	BEGIN	SET	j = i - 1	SET	$pa(~%i%~ ~off~)	= $pa(~%j%~ ~off~) + $pa(~%j%~ ~size~)	WRITE_LONG	(0x426 + i * 4)	$pa(~%i%~ ~off~)	WRITE_ASCIIE	$pa(~%i%~ ~off~)	$pa(~%i%~)	END
			SET	ra_0_off	= pa_8_off + pa_8_size	WRITE_LONG	0x44a	ra_0_off	WRITE_ASCIIE	ra_0_off	~%ra_0%~
			FOR	(i = 1; i < 9; ++i)	BEGIN	SET	j = i - 1	SET	$ra(~%i%~ ~off~)	= $ra(~%j%~ ~off~) + $ra(~%j%~ ~size~)	WRITE_LONG	(0x44a + i * 4)	$ra(~%i%~ ~off~)	WRITE_ASCIIE	$ra(~%i%~ ~off~)	$ra(~%i%~)	END
			SET	so_0_off	= ra_8_off + ra_8_size	WRITE_LONG	0x46e	so_0_off	WRITE_ASCIIE	so_0_off	~%so_0%~
			FOR	(i = 1; i < 9; ++i)	BEGIN	SET	j = i - 1	SET	$so(~%i%~ ~off~)	= $so(~%j%~ ~off~) + $so(~%j%~ ~size~)	WRITE_LONG	(0x46e + i * 4)	$so(~%i%~ ~off~)	WRITE_ASCIIE	$so(~%i%~ ~off~)	$so(~%i%~)	END
			SET	wi_0_off	= so_8_off + so_8_size	WRITE_LONG	0x492	wi_0_off	WRITE_ASCIIE	wi_0_off	~%wi_0%~
			FOR	(i = 1; i < 9; ++i)	BEGIN	SET	j = i - 1	SET	$wi(~%i%~ ~off~)	= $wi(~%j%~ ~off~) + $wi(~%j%~ ~size~)	WRITE_LONG	(0x492 + i * 4)	$wi(~%i%~ ~off~)	WRITE_ASCIIE	$wi(~%i%~ ~off~)	$wi(~%i%~)	END
			SET	do_0_off	= wi_8_off + wi_8_size	WRITE_LONG	0x5b2	do_0_off	WRITE_ASCIIE	do_0_off	~%do_0%~
			FOR	(i = 1; i < 9; ++i)	BEGIN	SET	j = i - 1	SET	$do(~%i%~ ~off~)	= $do(~%j%~ ~off~) + $do(~%j%~ ~size~)	WRITE_LONG	(0x5b2 + i * 4)	$do(~%i%~ ~off~)	WRITE_ASCIIE	$do(~%i%~ ~off~)	$do(~%i%~)	END
				
			SET	ab_off	= do_8_off + do_8_size	WRITE_LONG	0x5fa	ab_off	WRITE_ASCIIE	ab_off	~%abilities%~
			SET	sng_off	= ab_off + ab_size			WRITE_LONG	0x602	sng_off	WRITE_ASCIIE	sng_off	~%songs%~
			SET	shp_off	= sng_off + sng_size		WRITE_LONG	0x60a	shp_off	WRITE_ASCIIE	shp_off	~%shapes%~
			SET	slt_off	= shp_off + shp_size		WRITE_LONG	0x612	slt_off	WRITE_ASCIIE	slt_off	~%slots%~
			SET	itm_off	= slt_off + 0x68				WRITE_LONG	0x616	itm_off	WRITE_ASCIIE	itm_off	~%items%~
			SET	fx_off	= itm_off + itm_size		WRITE_LONG	0x61e	fx_off	WRITE_ASCIIE	fx_off	~%effects%~
		END
	END
	
	

DEFINE_PATCH_FUNCTION ~REPLACE_AREA_ITEM_IWD2~
	INT_VAR
		single_match=0
		charges1=~-1~
		charges2=~-1~
		charges3=~-1~
	STR_VAR
		old_item=~~
		new_item=~~
		flags=~same~
BEGIN
	SET item_name_length = (STRING_LENGTH ~%old_item%~)
	PATCH_IF (~%flags%~ STRING_EQUAL_CASE ~same~) BEGIN
		SET flag = 0xDEFA
	END ELSE BEGIN
	SET	flag = 0
	PATCH_IF	! ~%flags%~	STRING_CONTAINS_REGEXP	~identified~	BEGIN SET	flag |= 1	END
	PATCH_IF	! ~%flags%~	STRING_CONTAINS_REGEXP	~unstealable~	BEGIN SET	flag |= 2	END
	PATCH_IF	! ~%flags%~	STRING_CONTAINS_REGEXP	~stolen~		BEGIN SET	flag |= 4	END
	PATCH_IF	! ~%flags%~	STRING_CONTAINS_REGEXP	~undroppable~	BEGIN SET	flag |= 8	END
	END
	SET item_found = 0
	READ_SHORT 0x86 itemnumber
	READ_LONG 0x88 itemoffset
	FOR (i = 0; i < itemnumber; ++i) BEGIN
		SET offset = itemoffset + (i * 0x14)
		READ_ASCII offset name_of_item (item_name_length)
		PATCH_IF (~%name_of_item%~ STRING_EQUAL_CASE ~%old_item%~) BEGIN
			item_found = 1
			WRITE_ASCIIE offset ~%new_item%~ #8
			PATCH_IF (charges1 != (0 - 1)) BEGIN
				WRITE_SHORT (offset + 0xa) charges1
			END
			PATCH_IF (charges2 != (0 - 1)) BEGIN
				WRITE_SHORT (offset + 0xc) charges2
			END
			PATCH_IF (charges3 != (0 - 1)) BEGIN
				WRITE_SHORT (offset + 0xe) charges3
			END
			PATCH_IF (flag != 0xDEFA) BEGIN
				WRITE_LONG (offset + 0x10) flag
			END


			PATCH_IF (single_match = 1) BEGIN
				i = itemnumber
			END
			
		END
	END
	PATCH_IF (item_found = 0) BEGIN
		PATCH_WARN ~No item called %old_item% was found.~
	END

END

DEFINE_PATCH_FUNCTION ~CONVERT_DLG_TO_IWD2_FORMAT~
BEGIN
	READ_LONG 0xc ulgiash
	PATCH_IF (ulgiash = 0x34) BEGIN
		DELETE_BYTES 0x30 4

		READ_LONG 0xc ulgiash
		ulgiash -= 4
		WRITE_LONG 0xc ulgiash
	
		READ_LONG 0x14 ulgiash
		ulgiash -= 4
		WRITE_LONG 0x14 ulgiash
	
		READ_LONG 0x18 ulgiash
		ulgiash -= 4
		WRITE_LONG 0x18 ulgiash
		READ_LONG ulgiash ulgiash
		INSERT_BYTES (ulgiash - 2) 2
		
		READ_LONG 0x20 ulgiash
		ulgiash -= 4
		WRITE_LONG 0x20 ulgiash
	
		READ_LONG 0x28 ulgiash
		ulgiash -= 4
		WRITE_LONG 0x28 ulgiash
		READ_LONG ulgiash ulgiash
		INSERT_BYTES (ulgiash - 2) 2
	END

END

COPY ~%mod_folder%/itm/itm_item_revisions~ ~override~

COPY ~%mod_folder%/bam/bam_item_revisions~ ~override~

ACTION_IF !(FILE_EXISTS USALBEET.bam) BEGIN
	COPY ~%mod_folder%/bam/USALBEET.bam~ ~override~
	COPY ~%mod_folder%/bam/USALBEH3.bam~ ~override~
	COPY ~%mod_folder%/bam/USALBITT.bam~ ~override~
	COPY ~%mod_folder%/bam/USALBLAC.bam~ ~override~
	COPY ~%mod_folder%/bam/USALBLOO.bam~ ~override~
	COPY ~%mod_folder%/bam/USALBOGV.bam~ ~override~
	COPY ~%mod_folder%/bam/USALBON2.bam~ ~override~
	COPY ~%mod_folder%/bam/USALBRIN.bam~ ~override~
	COPY ~%mod_folder%/bam/USALBUR3.bam~ ~override~
	COPY ~%mod_folder%/bam/USALCLAR.bam~ ~override~
	COPY ~%mod_folder%/bam/USALCOR2.bam~ ~override~
	COPY ~%mod_folder%/bam/USALECTO.bam~ ~override~
	COPY ~%mod_folder%/bam/USALELEC.bam~ ~override~
	COPY ~%mod_folder%/bam/USALFAI2.bam~ ~override~
	COPY ~%mod_folder%/bam/USALFEY3.bam~ ~override~
	COPY ~%mod_folder%/bam/USALFIRE.bam~ ~override~
	COPY ~%mod_folder%/bam/USALFISH.bam~ ~override~
	COPY ~%mod_folder%/bam/USALFIZZ.bam~ ~override~
	COPY ~%mod_folder%/bam/USALFROS.bam~ ~override~
	COPY ~%mod_folder%/bam/USALGHOU.bam~ ~override~
	COPY ~%mod_folder%/bam/USALGOL2.bam~ ~override~
	COPY ~%mod_folder%/bam/USALLIME.bam~ ~override~
	COPY ~%mod_folder%/bam/USALMAGN.bam~ ~override~
	COPY ~%mod_folder%/bam/USALMURK.bam~ ~override~
	COPY ~%mod_folder%/bam/USALMUSK.bam~ ~override~
	COPY ~%mod_folder%/bam/USALOGRE.bam~ ~override~
	COPY ~%mod_folder%/bam/USALOILS.bam~ ~override~
	COPY ~%mod_folder%/bam/USALPLAS.bam~ ~override~
	COPY ~%mod_folder%/bam/USALPRES.bam~ ~override~
	COPY ~%mod_folder%/bam/USALRAD3.bam~ ~override~
	COPY ~%mod_folder%/bam/USALRAI2.bam~ ~override~
	COPY ~%mod_folder%/bam/USALSMOK.bam~ ~override~
	COPY ~%mod_folder%/bam/USALSNAI.bam~ ~override~
	COPY ~%mod_folder%/bam/USALSNAK.bam~ ~override~
	COPY ~%mod_folder%/bam/USALSOUR.bam~ ~override~
	COPY ~%mod_folder%/bam/USALSWEE.bam~ ~override~
	COPY ~%mod_folder%/bam/USALTREE.bam~ ~override~
	COPY ~%mod_folder%/bam/USALTROL.bam~ ~override~
	COPY ~%mod_folder%/bam/USALVAMP.bam~ ~override~
	COPY ~%mod_folder%/bam/USALVIAL.bam~ ~override~
	COPY ~%mod_folder%/bam/USALZOMB.bam~ ~override~
END

COPY ~%mod_folder%/spl/spl_item_revisions~ ~override~

COPY ~%mod_folder%/eff/eff_item_revisions~ ~override~

COPY_EXISTING ~00AMUL12.itm~ ~override~
	SAY IDENTIFIED_DESC @10021

COPY_EXISTING ~00AMUL13.itm~ ~override~
	SAY IDENTIFIED_DESC @10023

COPY_EXISTING ~00AMUL14.itm~ ~override~
	SAY IDENTIFIED_DESC @10025

COPY_EXISTING ~00AMUL15.itm~ ~override~
	SAY IDENTIFIED_DESC @10027

COPY_EXISTING ~00AMUL30.itm~ ~override~
	SAY IDENTIFIED_DESC @10029

COPY_EXISTING ~00AMUL32.itm~ ~override~
	SAY IDENTIFIED_DESC @10035

COPY_EXISTING ~00AMULBT.itm~ ~override~
	SAY IDENTIFIED_DESC @10037

COPY_EXISTING ~00HFAMBT.itm~ ~override~
	SAY IDENTIFIED_DESC @10039

COPY_EXISTING ~00AMULDS.itm~ ~override~
	SAY IDENTIFIED_DESC @10041

COPY_EXISTING ~00HFAMDS.itm~ ~override~
	SAY IDENTIFIED_DESC @10043

COPY_EXISTING ~00AMULES.itm~ ~override~
	SAY IDENTIFIED_DESC @10045

COPY_EXISTING ~00HFAMES.itm~ ~override~
	SAY IDENTIFIED_DESC @10047

COPY_EXISTING ~00AMULFD.itm~ ~override~
	SAY IDENTIFIED_DESC @10049

COPY_EXISTING ~00HFAMFD.itm~ ~override~
	SAY IDENTIFIED_DESC @10051

COPY_EXISTING ~00AMULGC.itm~ ~override~
	SAY IDENTIFIED_DESC @10053

COPY_EXISTING ~00HFAMGC.itm~ ~override~
	SAY IDENTIFIED_DESC @10055

COPY_EXISTING ~00AMULMP.itm~ ~override~
	SAY IDENTIFIED_DESC @10057

COPY_EXISTING ~00HFAMMP.itm~ ~override~
	SAY IDENTIFIED_DESC @10059

COPY_EXISTING ~00AMULSL.itm~ ~override~
	SAY IDENTIFIED_DESC @10061

COPY_EXISTING ~00HFAMSL.itm~ ~override~
	SAY IDENTIFIED_DESC @10063

COPY_EXISTING ~00POTNBI.itm~ ~override~ //Blood of the Innocent - it's an amulet, not a potion
	SAY IDENTIFIED_DESC @10065

COPY_EXISTING ~00HFPNBI.itm~ ~override~
	SAY IDENTIFIED_DESC @10067

COPY_EXISTING ~11AMULCM.itm~ ~override~
	SAY IDENTIFIED_DESC @10069

COPY_EXISTING ~11HFAMCM.itm~ ~override~
	SAY NAME2 @10070

COPY_EXISTING ~12AMULHC.itm~ ~override~
	SAY IDENTIFIED_DESC @10073

COPY_EXISTING ~12HFAMHC.itm~ ~override~
	SAY IDENTIFIED_DESC @10075

COPY_EXISTING ~53AMULBS.itm~ ~override~
	SAY IDENTIFIED_DESC @10077

COPY_EXISTING ~USHFAMBS.itm~ ~override~
	SAY IDENTIFIED_DESC @10079

COPY_EXISTING ~53AMULHD.itm~ ~override~
	SAY IDENTIFIED_DESC @10081

COPY_EXISTING ~USHFAMHD.itm~ ~override~
	SAY IDENTIFIED_DESC @10083

COPY_EXISTING ~00RING15.itm~ ~override~
	SAY IDENTIFIED_DESC @10085

COPY_EXISTING ~00RING16.itm~ ~override~
	SAY IDENTIFIED_DESC @10087

COPY_EXISTING ~00RING17.itm~ ~override~
	SAY NAME2 @10088
	SAY IDENTIFIED_DESC @10089

COPY_EXISTING ~00RING18.itm~ ~override~
	SAY IDENTIFIED_DESC @10091

COPY_EXISTING ~00RING20.itm~ ~override~
	SAY NAME2 @10094
	SAY IDENTIFIED_DESC @10095

COPY_EXISTING ~00RING21.itm~ ~override~
	SAY NAME2 @10096
	SAY IDENTIFIED_DESC @10097

COPY_EXISTING ~00RING23.itm~ ~override~
	SAY IDENTIFIED_DESC @10101

COPY_EXISTING ~00RING25.itm~ ~override~
	SAY IDENTIFIED_DESC @10103

COPY_EXISTING ~00RING67.itm~ ~override~
	SAY IDENTIFIED_DESC @10105

COPY_EXISTING ~00RING68.itm~ ~override~
	SAY IDENTIFIED_DESC @10107

COPY_EXISTING ~00RING69.itm~ ~override~
	SAY NAME2 @10108
	SAY IDENTIFIED_DESC @10109

COPY_EXISTING ~00RING70.itm~ ~override~
	SAY NAME2 @10110
	SAY IDENTIFIED_DESC @10111

COPY_EXISTING ~00RING71.itm~ ~override~
	SAY IDENTIFIED_DESC @10113

COPY_EXISTING ~00RING72.itm~ ~override~
	SAY IDENTIFIED_DESC @10115

COPY_EXISTING ~00RING73.itm~ ~override~
	SAY NAME2 @10116
	SAY IDENTIFIED_DESC @10117

COPY_EXISTING ~00RING74.itm~ ~override~
	SAY IDENTIFIED_DESC @10119

COPY_EXISTING ~00RING75.itm~ ~override~
	SAY IDENTIFIED_DESC @10121

COPY_EXISTING ~00RING76.itm~ ~override~
	SAY NAME2 @10122
	SAY IDENTIFIED_DESC @10123

COPY_EXISTING ~00RING77.itm~ ~override~
	SAY NAME2 @10124
	SAY IDENTIFIED_DESC @10125

COPY_EXISTING ~00RING78.itm~ ~override~
	SAY NAME2 @10126
	SAY IDENTIFIED_DESC @10127

COPY_EXISTING ~00RING79.itm~ ~override~
	SAY NAME2 @10128
	SAY IDENTIFIED_DESC @10129

COPY_EXISTING ~00RING80.itm~ ~override~
	SAY NAME2 @10130
	SAY IDENTIFIED_DESC @10131

COPY_EXISTING ~00RING82.itm~ ~override~
	SAY NAME2 @10134
	SAY IDENTIFIED_DESC @10135

COPY_EXISTING ~00RING83.itm~ ~override~
	SAY IDENTIFIED_DESC @10137

COPY_EXISTING ~00RING84.itm~ ~override~
	SAY IDENTIFIED_DESC @10139

COPY_EXISTING ~00RING85.itm~ ~override~
	SAY NAME2 @10140
	SAY IDENTIFIED_DESC @10141

COPY_EXISTING ~00RING86.itm~ ~override~
	SAY IDENTIFIED_DESC @10143

COPY_EXISTING ~00RING87.itm~ ~override~
	SAY IDENTIFIED_DESC @10145

COPY_EXISTING ~00RING88.itm~ ~override~
	SAY IDENTIFIED_DESC @10147

COPY_EXISTING ~00RING89.itm~ ~override~
	SAY IDENTIFIED_DESC @10149

COPY_EXISTING ~00RING90.itm~ ~override~
	SAY NAME2 @10150
	SAY IDENTIFIED_DESC @10151

COPY_EXISTING ~00RING91.itm~ ~override~
	SAY NAME2 @10152
	SAY IDENTIFIED_DESC @10153

COPY_EXISTING ~00RING92.itm~ ~override~
	SAY NAME2 @10154
	SAY IDENTIFIED_DESC @10155

COPY_EXISTING ~00RING93.itm~ ~override~
	SAY NAME2 @10156
	SAY IDENTIFIED_DESC @10157

COPY_EXISTING ~00RING94.itm~ ~override~
	SAY NAME2 @10158
	SAY IDENTIFIED_DESC @10159

COPY_EXISTING ~00RING95.itm~ ~override~
	SAY IDENTIFIED_DESC @10161

COPY_EXISTING ~00RING96.itm~ ~override~
	SAY NAME2 @10162
	SAY IDENTIFIED_DESC @10163

COPY_EXISTING ~00RING97.itm~ ~override~
	SAY IDENTIFIED_DESC @10165

COPY_EXISTING ~00RING98.itm~ ~override~
	SAY IDENTIFIED_DESC @10167

COPY_EXISTING ~00RINGAR.itm~ ~override~
	SAY IDENTIFIED_DESC @10169

COPY_EXISTING ~00HFRGAR.itm~ ~override~
	SAY IDENTIFIED_DESC @10171

COPY_EXISTING ~00RINGCR.itm~ ~override~
	SAY IDENTIFIED_DESC @10173

COPY_EXISTING ~00HFRGCR.itm~ ~override~
	SAY IDENTIFIED_DESC @10175

COPY_EXISTING ~00RINGTB.itm~ ~override~
	SAY IDENTIFIED_DESC @10181

COPY_EXISTING ~00HFRGTB.itm~ ~override~
	SAY IDENTIFIED_DESC @10183

COPY_EXISTING ~41RINGRA.itm~ ~override~
	PATCH_IF (MOD_IS_INSTALLED ~iwd2ee.tp2~ ~2~) BEGIN //If Spell Revisions is installed
		SAY IDENTIFIED_DESC @10187
	END ELSE BEGIN
		SAY IDENTIFIED_DESC @10185
	END

COPY_EXISTING ~41HFRGRA.itm~ ~override~
	SAY IDENTIFIED_DESC @10189

COPY_EXISTING ~00BOOT01.itm~ ~override~
	SAY IDENTIFIED_DESC @10191

COPY_EXISTING ~00BOOT02.itm~ ~override~
	SAY IDENTIFIED_DESC @10193

COPY_EXISTING ~00BOOT09.itm~ ~override~
	SAY IDENTIFIED_DESC @10201

COPY_EXISTING ~00BOOT15.itm~ ~override~
	SAY IDENTIFIED_DESC @10205

COPY_EXISTING ~00HFBTCS.itm~ ~override~
	SAY NAME2 @10208
	SAY IDENTIFIED_DESC @10209

COPY_EXISTING ~00BOOTSB.itm~ ~override~
	SAY IDENTIFIED_DESC @10211

COPY_EXISTING ~00HFBTSB.itm~ ~override~
	SAY IDENTIFIED_DESC @10213

COPY_EXISTING ~10BOOTTB.itm~ ~override~
	SAY IDENTIFIED_DESC @10215

COPY_EXISTING ~10HFBTTB.itm~ ~override~
	SAY IDENTIFIED_DESC @10217

COPY_EXISTING ~50BOOT14.itm~ ~override~
	SAY IDENTIFIED_DESC @10219

COPY_EXISTING ~USHFBTWH.itm~ ~override~
	SAY IDENTIFIED_DESC @10221

COPY_EXISTING ~00BRAC11.itm~ ~override~
	SAY IDENTIFIED_DESC @10237

COPY_EXISTING ~00BRAC18.itm~ ~override~
	SAY IDENTIFIED_DESC @10243

COPY_EXISTING ~00BRACBB.itm~ ~override~
	SAY IDENTIFIED_DESC @10245

COPY_EXISTING ~00HFBCBB.itm~ ~override~
	SAY IDENTIFIED_DESC @10247

COPY_EXISTING ~00BRACLA.itm~ ~override~
	SAY IDENTIFIED_DESC @10253

COPY_EXISTING ~00HFBCLA.itm~ ~override~
	SAY IDENTIFIED_DESC @10255

COPY_EXISTING ~00BRACRB.itm~ ~override~
	SAY IDENTIFIED_DESC @10257

COPY_EXISTING ~00HFBCRB.itm~ ~override~
	SAY IDENTIFIED_DESC @10259

COPY_EXISTING ~00BRACTB.itm~ ~override~
	SAY IDENTIFIED_DESC @10261

COPY_EXISTING ~00HFBCTB.itm~ ~override~
	SAY IDENTIFIED_DESC @10263

COPY_EXISTING ~40GENPWC.itm~ ~override~
	SAY IDENTIFIED_DESC @10269

COPY_EXISTING ~USHFGNWC.itm~ ~override~
	SAY IDENTIFIED_DESC @10271

COPY_EXISTING ~USHFBT05.itm~ ~override~
	SAY NAME2 @10280
	SAY IDENTIFIED_DESC @10281

COPY_EXISTING ~00BELTAD.itm~ ~override~
	SAY IDENTIFIED_DESC @10283

COPY_EXISTING ~00HFBTAD.itm~ ~override~
	SAY IDENTIFIED_DESC @10285

COPY_EXISTING ~00BELTBG.itm~ ~override~
	SAY IDENTIFIED_DESC @10287

COPY_EXISTING ~00HFBTBG.itm~ ~override~
	SAY IDENTIFIED_DESC @10289

COPY_EXISTING ~00BELTDB.itm~ ~override~
	SAY NAME2 @10290
	SAY IDENTIFIED_DESC @10291

COPY_EXISTING ~00HFBTDB.itm~ ~override~
	SAY NAME2 @10292
	SAY IDENTIFIED_DESC @10293

COPY_EXISTING ~00HFBTLG.itm~ ~override~
	SAY IDENTIFIED_DESC @10297

COPY_EXISTING ~00BELTSS.itm~ ~override~
	SAY IDENTIFIED_DESC @10299

COPY_EXISTING ~00HFBTSS.itm~ ~override~
	SAY IDENTIFIED_DESC @10301

COPY_EXISTING ~11BELTMK.itm~ ~override~
	SAY IDENTIFIED_DESC @10303

COPY_EXISTING ~USHFBTMK.itm~ ~override~
	SAY IDENTIFIED_DESC @10305

COPY_EXISTING ~00CLCK17.itm~ ~override~
	SAY IDENTIFIED_DESC @10321

COPY_EXISTING ~00CLCK18.itm~ ~override~
	SAY IDENTIFIED_DESC @10323

COPY_EXISTING ~00CLCKBC.itm~ ~override~
	SAY IDENTIFIED_DESC @10325

COPY_EXISTING ~00HFCKBC.itm~ ~override~
	SAY IDENTIFIED_DESC @10327

COPY_EXISTING ~00CLCKFC.itm~ ~override~
	SAY IDENTIFIED_DESC @10329

COPY_EXISTING ~00HFCKFC.itm~ ~override~
	SAY NAME2 @10330
	SAY IDENTIFIED_DESC @10331

COPY_EXISTING ~00HFCKMB.itm~ ~override~
	SAY IDENTIFIED_DESC @10335

COPY_EXISTING ~00CLCKNV.itm~ ~override~
	SAY IDENTIFIED_DESC @10337

COPY_EXISTING ~00HFCKNV.itm~ ~override~
	SAY IDENTIFIED_DESC @10339

COPY_EXISTING ~00CLCKSB.itm~ ~override~
	SAY IDENTIFIED_DESC @10341

COPY_EXISTING ~00HFCKSB.itm~ ~override~
	SAY IDENTIFIED_DESC @10343

COPY_EXISTING ~00CLCKWC.itm~ ~override~
	SAY IDENTIFIED_DESC @10345

COPY_EXISTING ~00HFCKWC.itm~ ~override~
	SAY IDENTIFIED_DESC @10347

COPY_EXISTING ~50CLCK17.itm~ ~override~
	SAY IDENTIFIED_DESC @10349

COPY_EXISTING ~USHFCKWH.itm~ ~override~
	SAY IDENTIFIED_DESC @10351

COPY_EXISTING ~53CLCKHD.itm~ ~override~
	SAY IDENTIFIED_DESC @10353

COPY_EXISTING ~USHFCKWH.itm~ ~override~
	SAY IDENTIFIED_DESC @10355

COPY_EXISTING ~00HELM01.itm~ ~override~
	SAY UNIDENTIFIED_DESC @10357
	SAY IDENTIFIED_DESC @10357

COPY_EXISTING_REGEXP ~00HELM0[1-6].itm~ ~override~
	SAY UNIDENTIFIED_DESC @10358
	SAY IDENTIFIED_DESC @10358

COPY_EXISTING ~00HELM19.itm~ ~override~
	SAY IDENTIFIED_DESC @10362

COPY_EXISTING ~00HELMBH.itm~ ~override~
	SAY IDENTIFIED_DESC @10364

COPY_EXISTING ~00HFHMBH.itm~ ~override~
	SAY IDENTIFIED_DESC @10366

COPY_EXISTING ~00HELMDS.itm~ ~override~
	SAY IDENTIFIED_DESC @10368

COPY_EXISTING ~00HFHMDS.itm~ ~override~
	SAY IDENTIFIED_DESC @10370

COPY_EXISTING ~00HELMSC.itm~ ~override~
	SAY IDENTIFIED_DESC @10372

COPY_EXISTING ~00HFHMSC.itm~ ~override~
	SAY IDENTIFIED_DESC @10374

COPY_EXISTING ~00HFHMSM.itm~ ~override~
	SAY IDENTIFIED_DESC @10378

COPY_EXISTING ~51HELMWM.itm~ ~override~
	SAY IDENTIFIED_DESC @10380

COPY_EXISTING ~51HFHMWM.itm~ ~override~
	SAY IDENTIFIED_DESC @10382

COPY_EXISTING ~00ROBE01.itm~ ~override~
	SAY IDENTIFIED_DESC @10384

COPY_EXISTING ~00ROBE02.itm~ ~override~
	SAY IDENTIFIED_DESC @10386

COPY_EXISTING ~00ROBE03.itm~ ~override~
	SAY IDENTIFIED_DESC @10388

COPY_EXISTING ~00ROBE04.itm~ ~override~
	SAY IDENTIFIED_DESC @10390

COPY_EXISTING ~00ROBE05.itm~ ~override~
	SAY IDENTIFIED_DESC @10392

COPY_EXISTING ~00ROBE06.itm~ ~override~
	SAY IDENTIFIED_DESC @10394

COPY_EXISTING ~00ROBE07.itm~ ~override~
	SAY IDENTIFIED_DESC @10396

COPY_EXISTING ~00ROBE15.itm~ ~override~
	SAY IDENTIFIED_DESC @10398

COPY_EXISTING ~00ROBE16.itm~ ~override~
	SAY IDENTIFIED_DESC @10400

COPY_EXISTING ~00ROBE99.itm~ ~override~
	SAY IDENTIFIED_DESC @10402

COPY_EXISTING ~00ROBEMR.itm~ ~override~
	SAY IDENTIFIED_DESC @10404

COPY_EXISTING ~00HFRBMR.itm~ ~override~
	SAY IDENTIFIED_DESC @10406

COPY_EXISTING ~00ROBERA.itm~ ~override~
	SAY IDENTIFIED_DESC @10408

COPY_EXISTING ~00HFRBRA.itm~ ~override~
	SAY IDENTIFIED_DESC @10410

COPY_EXISTING ~11ROBEPR.itm~ ~override~
	SAY IDENTIFIED_DESC @10412

COPY_EXISTING ~11HFRBPR.itm~ ~override~
	SAY IDENTIFIED_DESC @10414

COPY_EXISTING ~00LEAT05.itm~ ~override~
	SAY IDENTIFIED_DESC @10424

COPY_EXISTING ~00LEAT06.itm~ ~override~
	SAY NAME2 @10425
	SAY IDENTIFIED_DESC @10426

COPY_EXISTING ~00LEAT07.itm~ ~override~
	SAY IDENTIFIED_DESC @10428

COPY_EXISTING ~00LEAT08.itm~ ~override~
	SAY NAME2 @10429
	SAY IDENTIFIED_DESC @10430

COPY_EXISTING ~00LEAT86.itm~ ~override~
	SAY NAME2 @10431
	SAY IDENTIFIED_DESC @10432

COPY_EXISTING ~00LEAT87.itm~ ~override~
	SAY NAME2 @10433
	SAY IDENTIFIED_DESC @10434

COPY_EXISTING ~00LEAT88.itm~ ~override~
	SAY NAME2 @10435
	SAY IDENTIFIED_DESC @10436

COPY_EXISTING ~00LEAT89.itm~ ~override~
	SAY IDENTIFIED_DESC @10438

COPY_EXISTING ~00LEAT90.itm~ ~override~
	SAY NAME2 @10439
	SAY IDENTIFIED_DESC @10440

COPY_EXISTING ~00LEAT91.itm~ ~override~
	SAY NAME2 @10441
	SAY IDENTIFIED_DESC @10442

COPY_EXISTING ~00LEAT92.itm~ ~override~
	SAY NAME2 @10443
	SAY IDENTIFIED_DESC @10444

COPY_EXISTING ~00LEAT93.itm~ ~override~
	SAY NAME2 @10445
	SAY IDENTIFIED_DESC @10446

COPY_EXISTING ~00LEAT94.itm~ ~override~
	SAY NAME2 @10447
	SAY IDENTIFIED_DESC @10448

COPY_EXISTING ~00LEAT95.itm~ ~override~
	SAY NAME2 @10449
	SAY IDENTIFIED_DESC @10450

COPY_EXISTING ~00LEAT96.itm~ ~override~
	SAY NAME2 @10451
	SAY IDENTIFIED_DESC @10452

COPY_EXISTING ~00LEAT97.itm~ ~override~
	SAY NAME2 @10453
	SAY IDENTIFIED_DESC @10454

COPY_EXISTING ~00LEAT98.itm~ ~override~
	SAY NAME2 @10455
	SAY IDENTIFIED_DESC @10456

COPY_EXISTING ~00LEAT99.itm~ ~override~
	SAY NAME2 @10457
	SAY IDENTIFIED_DESC @10458

COPY_EXISTING ~10LEATUB.itm~ ~override~
	SAY IDENTIFIED_DESC @10460

COPY_EXISTING ~10HFLTUB.itm~ ~override~
	SAY NAME2 @10461
	SAY IDENTIFIED_DESC @10462

COPY_EXISTING ~62LEATDB.itm~ ~override~
	SAY NAME2 @10463
	SAY IDENTIFIED_DESC @10464

COPY_EXISTING ~62HFLTDB.itm~ ~override~
	SAY NAME2 @10465
	SAY IDENTIFIED_DESC @10466

COPY_EXISTING ~50LEATMS.itm~ ~override~
	SAY NAME2 @10467
	SAY IDENTIFIED_DESC @10468

COPY_EXISTING ~50HFLTMS.itm~ ~override~
	SAY NAME2 @10469
	SAY IDENTIFIED_DESC @10470

COPY_EXISTING ~60LEATZU.itm~ ~override~
	SAY NAME2 @10471
	SAY IDENTIFIED_DESC @10472

COPY_EXISTING ~60HFLTZU.itm~ ~override~
	SAY NAME2 @10473
	SAY IDENTIFIED_DESC @10474

COPY_EXISTING ~60LEATIN.itm~ ~override~
	SAY NAME2 @10475
	SAY IDENTIFIED_DESC @10476

COPY_EXISTING ~60HFLTIN.itm~ ~override~
	SAY NAME2 @10477
	SAY IDENTIFIED_DESC @10478

COPY_EXISTING ~00HIDE01.itm~ ~override~
	SAY IDENTIFIED_DESC @10480

COPY_EXISTING ~00HIDE02.itm~ ~override~
	SAY IDENTIFIED_DESC @10482

COPY_EXISTING ~00HIDE03.itm~ ~override~
	SAY IDENTIFIED_DESC @10484

COPY_EXISTING ~00HIDE04.itm~ ~override~
	SAY IDENTIFIED_DESC @10486

COPY_EXISTING ~USHFHD04.itm~ ~override~
	SAY NAME2 @10487
	SAY IDENTIFIED_DESC @10488

COPY_EXISTING ~00HIDE05.itm~ ~override~
	SAY IDENTIFIED_DESC @10490

COPY_EXISTING ~50HIDE06.itm~ ~override~
	SAY NAME2 @10493
	SAY IDENTIFIED_DESC @10494

COPY_EXISTING ~USHFHDWH.itm~ ~override~
	SAY NAME2 @10495
	SAY IDENTIFIED_DESC @10496

COPY_EXISTING ~50HIDEAH.itm~ ~override~
	SAY IDENTIFIED_DESC @10498

COPY_EXISTING ~50HFHEAH.itm~ ~override~
	SAY NAME2 @10499
	SAY IDENTIFIED_DESC @10500

COPY_EXISTING ~00CHAN02.itm~ ~override~
	SAY IDENTIFIED_DESC @10504

COPY_EXISTING ~00CHAN03.itm~ ~override~
	SAY IDENTIFIED_DESC @10506

COPY_EXISTING ~00CHAN06.itm~ ~override~
	SAY NAME2 @10511
	SAY IDENTIFIED_DESC @10512

COPY_EXISTING ~00CHAN07.itm~ ~override~
	SAY NAME2 @10515
	SAY IDENTIFIED_DESC @10516

COPY_EXISTING ~00CHAN08.itm~ ~override~
	SAY NAME2 @10517
	SAY IDENTIFIED_DESC @10518

COPY_EXISTING ~00CHAN09.itm~ ~override~
	SAY NAME2 @10521
	SAY IDENTIFIED_DESC @10522

COPY_EXISTING ~00CHANML.itm~ ~override~
	SAY NAME2 @10525
	SAY IDENTIFIED_DESC @10526

COPY_EXISTING ~00HFCNML.itm~ ~override~
	SAY NAME2 @10527
	SAY IDENTIFIED_DESC @10528

COPY_EXISTING ~60CHANCD.itm~ ~override~
	SAY NAME2 @10529

COPY_EXISTING ~60HFCNCD.itm~ ~override~
	SAY NAME2 @10531

COPY_EXISTING ~60CHANSA.itm~ ~override~
	SAY NAME2 @10533
	SAY IDENTIFIED_DESC @10534

COPY_EXISTING ~60HFCNSA.itm~ ~override~
	SAY NAME2 @10535
	SAY IDENTIFIED_DESC @10536

COPY_EXISTING ~60CHANTM.itm~ ~override~
	SAY NAME2 @10537
	SAY IDENTIFIED_DESC @10538

COPY_EXISTING ~60HFCNTM.itm~ ~override~
	SAY NAME2 @10539
	SAY IDENTIFIED_DESC @10540

COPY_EXISTING ~60CHANGR.itm~ ~override~
	SAY NAME2 @10541
	SAY IDENTIFIED_DESC @10542

COPY_EXISTING ~60HFCNGR.itm~ ~override~
	SAY NAME2 @10543
	SAY IDENTIFIED_DESC @10544

COPY_EXISTING ~00PLAT02.itm~ ~override~
	SAY IDENTIFIED_DESC @10548

COPY_EXISTING ~00PLAT03.itm~ ~override~
	SAY NAME2 @10549
	SAY IDENTIFIED_DESC @10550

COPY_EXISTING ~00PLAT04.itm~ ~override~
	SAY IDENTIFIED_DESC @10552

COPY_EXISTING ~00PLAT10.itm~ ~override~
	SAY IDENTIFIED_DESC @10554

COPY_EXISTING ~00PLAT12.itm~ ~override~
	SAY NAME2 @10557

COPY_EXISTING ~51PLAT10.itm~ ~override~
	SAY NAME2 @10559
	SAY IDENTIFIED_DESC @10560

COPY_EXISTING ~51HFPT10.itm~ ~override~
	SAY NAME2 @10561
	SAY IDENTIFIED_DESC @10562

COPY_EXISTING ~60PLATOF.itm~ ~override~
	SAY IDENTIFIED_DESC @10564

COPY_EXISTING ~60HFPTOF.itm~ ~override~
	SAY NAME2 @10565
	SAY IDENTIFIED_DESC @10566

COPY_EXISTING ~60PLATKC.itm~ ~override~
	SAY NAME2 @10567
	SAY IDENTIFIED_DESC @10568

COPY_EXISTING ~60HFPTKC.itm~ ~override~
	SAY NAME2 @10569
	SAY IDENTIFIED_DESC @10570

COPY_EXISTING ~60PLATPF.itm~ ~override~
	SAY NAME2 @10571
	SAY IDENTIFIED_DESC @10572

COPY_EXISTING ~60HFPTPF.itm~ ~override~
	SAY NAME2 @10573
	SAY IDENTIFIED_DESC @10574

COPY_EXISTING ~60PLATAG.itm~ ~override~
	SAY NAME2 @10575
	SAY IDENTIFIED_DESC @10576

COPY_EXISTING ~60HFPTAG.itm~ ~override~
	SAY NAME2 @10577
	PATCH_IF (MOD_IS_INSTALLED ~iwd2ee.tp2~ ~2~) BEGIN //If Spell Revisions is installed
		SAY IDENTIFIED_DESC @10580
	END ELSE BEGIN
		SAY IDENTIFIED_DESC @10578
	END

COPY_EXISTING ~60PLATDC.itm~ ~override~
	SAY NAME2 @10581
	SAY IDENTIFIED_DESC @10582

COPY_EXISTING ~60HFPTDC.itm~ ~override~
	SAY NAME2 @10583
	SAY IDENTIFIED_DESC @10584

COPY_EXISTING ~60PLATAA.itm~ ~override~
	SAY NAME2 @10585

COPY_EXISTING ~60HFPTAA.itm~ ~override~
	SAY NAME2 @10587
	SAY IDENTIFIED_DESC @10588

COPY_EXISTING ~00SHLD16.itm~ ~override~
	SAY IDENTIFIED_DESC @10602

COPY_EXISTING ~00SHLD17.itm~ ~override~
	SAY IDENTIFIED_DESC @10604

COPY_EXISTING ~00SHLD85.itm~ ~override~
	SAY NAME2 @10605
	SAY IDENTIFIED_DESC @10606

COPY_EXISTING ~00SHLD86.itm~ ~override~
	SAY NAME2 @10607
	SAY IDENTIFIED_DESC @10608

COPY_EXISTING ~00SHLD87.itm~ ~override~
	SAY NAME2 @10609
	SAY IDENTIFIED_DESC @10610

COPY_EXISTING ~00SHLD88.itm~ ~override~
	SAY NAME2 @10611
	SAY IDENTIFIED_DESC @10612

COPY_EXISTING ~00SHLD89.itm~ ~override~
	SAY NAME2 @10613
	SAY IDENTIFIED_DESC @10614

COPY_EXISTING ~00SHLD90.itm~ ~override~
	SAY NAME2 @10615
	SAY IDENTIFIED_DESC @10616

COPY_EXISTING ~00SHLD91.itm~ ~override~
	SAY NAME2 @10617
	SAY IDENTIFIED_DESC @10618

COPY_EXISTING ~00SHLD92.itm~ ~override~
	SAY NAME2 @10619
	SAY IDENTIFIED_DESC @10620

COPY_EXISTING ~00SHLD93.itm~ ~override~
	SAY IDENTIFIED_DESC @10622

COPY_EXISTING ~00SHLD94.itm~ ~override~
	SAY NAME2 @10623
	SAY IDENTIFIED_DESC @10624

COPY_EXISTING ~00SHLD95.itm~ ~override~
	SAY IDENTIFIED_DESC @10626

COPY_EXISTING ~00SHLD96.itm~ ~override~
	SAY NAME2 @10627
	SAY IDENTIFIED_DESC @10628

COPY_EXISTING ~00SHLD97.itm~ ~override~
	SAY IDENTIFIED_DESC @10630

COPY_EXISTING ~00SHLD98.itm~ ~override~
	SAY IDENTIFIED_DESC @10632

COPY_EXISTING ~00SHLD99.itm~ ~override~
	SAY IDENTIFIED_DESC @10634

COPY_EXISTING ~00SHLDBU.itm~ ~override~
	SAY NAME2 @10635
	SAY IDENTIFIED_DESC @10636

COPY_EXISTING ~00HFSDBU.itm~ ~override~
	SAY NAME2 @10637
	SAY IDENTIFIED_DESC @10638

COPY_EXISTING ~00SHLDFF.itm~ ~override~
	SAY NAME2 @10639
	SAY IDENTIFIED_DESC @10640

COPY_EXISTING ~00HFSDFF.itm~ ~override~
	SAY NAME2 @10641
	SAY IDENTIFIED_DESC @10642

COPY_EXISTING ~00SHLDFV.itm~ ~override~
	SAY IDENTIFIED_DESC @10644

COPY_EXISTING ~00HFSDFV.itm~ ~override~
	SAY NAME2 @10645
	SAY IDENTIFIED_DESC @10646

COPY_EXISTING ~00SHLDFF.itm~ ~override~
	SAY NAME2 @10647
	SAY IDENTIFIED_DESC @10648

COPY_EXISTING ~00HFSDFF.itm~ ~override~
	SAY NAME2 @10649
	SAY IDENTIFIED_DESC @10650

COPY_EXISTING ~00SHLDRF.itm~ ~override~
	SAY NAME2 @10651
	SAY IDENTIFIED_DESC @10652

COPY_EXISTING ~00HFSDRF.itm~ ~override~
	SAY NAME2 @10653
	SAY IDENTIFIED_DESC @10654

COPY_EXISTING ~12SHLDCT.itm~ ~override~
	SAY NAME2 @10655

COPY_EXISTING ~12HFSDCT.itm~ ~override~
	SAY NAME2 @10657

COPY_EXISTING ~12SHLDKD.itm~ ~override~
	SAY NAME2 @10659
	SAY IDENTIFIED_DESC @10660

COPY_EXISTING ~12HFSDKD.itm~ ~override~
	SAY NAME2 @10661
	SAY IDENTIFIED_DESC @10662

COPY_EXISTING ~12SHLDSG.itm~ ~override~
	SAY NAME2 @10663
	SAY IDENTIFIED_DESC @10664

COPY_EXISTING ~12HFSDSG.itm~ ~override~
	SAY NAME2 @10665
	SAY IDENTIFIED_DESC @10666

COPY_EXISTING ~12HFSDTS.itm~ ~override~
	SAY NAME2 @10669
	SAY IDENTIFIED_DESC @10670

COPY_EXISTING ~51SHLDFO.itm~ ~override~
	SAY NAME2 @10671
	SAY IDENTIFIED_DESC @10672

COPY_EXISTING ~51HFSDFO.itm~ ~override~
	SAY NAME2 @10673
	SAY IDENTIFIED_DESC @10674

COPY_EXISTING ~00DAGG05.itm~ ~override~
	SAY IDENTIFIED_DESC @10684

COPY_EXISTING ~00DAGG81.itm~ ~override~
	SAY IDENTIFIED_DESC @10688

COPY_EXISTING ~00DAGG82.itm~ ~override~
	SAY NAME2 @10689
	SAY IDENTIFIED_DESC @10690

COPY_EXISTING ~00DAGG84.itm~ ~override~
	SAY NAME2 @10693

COPY_EXISTING ~00DAGG90.itm~ ~override~
	SAY IDENTIFIED_DESC @10706

COPY_EXISTING ~00DAGG91.itm~ ~override~
	SAY IDENTIFIED_DESC @10708

COPY_EXISTING ~00DAGG92.itm~ ~override~
	SAY IDENTIFIED_DESC @10710

COPY_EXISTING ~00DAGG93.itm~ ~override~
	SAY NAME2 @10711
	SAY IDENTIFIED_DESC @10712

COPY_EXISTING ~00DAGG94.itm~ ~override~
	SAY NAME2 @10713
	SAY IDENTIFIED_DESC @10714

COPY_EXISTING ~00DAGG95.itm~ ~override~
	SAY IDENTIFIED_DESC @10716

COPY_EXISTING ~00DAGG96.itm~ ~override~
	SAY NAME2 @10717
	SAY IDENTIFIED_DESC @10718

COPY_EXISTING ~00DAGG97.itm~ ~override~
	SAY NAME2 @10719
	SAY IDENTIFIED_DESC @10720

COPY_EXISTING ~00DAGG98.itm~ ~override~
	SAY IDENTIFIED_DESC @10722

COPY_EXISTING ~00DAGG99.itm~ ~override~
	SAY IDENTIFIED_DESC @10724

COPY_EXISTING ~00DAGGFW.itm~ ~override~
	SAY IDENTIFIED_DESC @10726

COPY_EXISTING ~00HFDGFW.itm~ ~override~
	SAY IDENTIFIED_DESC @10728

COPY_EXISTING ~00DAGGPF.itm~ ~override~
	SAY IDENTIFIED_DESC @10730

COPY_EXISTING ~00HFDGPF.itm~ ~override~
	SAY IDENTIFIED_DESC @10732

COPY_EXISTING ~ZZL6GH.itm~ ~override~
	PATCH_IF (MOD_IS_INSTALLED ~iwd2ee.tp2~ ~24~) BEGIN //If Better Racial Enemies is installed
		SAY IDENTIFIED_DESC @10736
	END ELSE BEGIN
		SAY IDENTIFIED_DESC @10734
	END

COPY_EXISTING ~11HFDGGH.itm~ ~override~
	PATCH_IF (MOD_IS_INSTALLED ~iwd2ee.tp2~ ~24~) BEGIN //If Spell Revisions is installed
		SAY IDENTIFIED_DESC @10740
	END ELSE BEGIN
		SAY IDENTIFIED_DESC @10738
	END

COPY_EXISTING ~ZZJ5GT.itm~ ~override~
	SAY IDENTIFIED_DESC @10742

COPY_EXISTING ~ZZJ5HF.itm~ ~override~
	SAY IDENTIFIED_DESC @10744

COPY_EXISTING ~ZZJ5ST.itm~ ~override~
	SAY IDENTIFIED_DESC @10746

COPY_EXISTING ~ZZJ5HO.itm~ ~override~
	SAY IDENTIFIED_DESC @10748

COPY_EXISTING ~50HFDGLT.itm~ ~override~
	SAY IDENTIFIED_DESC @10752

COPY_EXISTING ~52DAGGSH.itm~ ~override~
	SAY IDENTIFIED_DESC @10754

COPY_EXISTING ~52HFDGSH.itm~ ~override~
	SAY IDENTIFIED_DESC @10756

COPY_EXISTING ~61DAGGWS.itm~ ~override~
	SAY IDENTIFIED_DESC @10758

COPY_EXISTING ~61HFDGWS.itm~ ~override~
	SAY IDENTIFIED_DESC @10760

COPY_EXISTING ~62DAGGXF.itm~ ~override~
	SAY IDENTIFIED_DESC @10762

COPY_EXISTING ~62HFDGXF.itm~ ~override~
	SAY IDENTIFIED_DESC @10764

COPY_EXISTING ~00SWDS05.itm~ ~override~
	SAY NAME2 @10773
	SAY IDENTIFIED_DESC @10774

COPY_EXISTING ~00SWDS85.itm~ ~override~
	SAY IDENTIFIED_DESC @10776

COPY_EXISTING ~00SWDS86.itm~ ~override~
	SAY NAME2 @10777
	SAY IDENTIFIED_DESC @10778

COPY_EXISTING ~00SWDS87.itm~ ~override~
	SAY IDENTIFIED_DESC @10780

COPY_EXISTING ~00SWDS92.itm~ ~override~
	SAY IDENTIFIED_DESC @10790

COPY_EXISTING ~00SWDS93.itm~ ~override~
	SAY IDENTIFIED_DESC @10792

COPY_EXISTING ~00SWDS94.itm~ ~override~
	SAY IDENTIFIED_DESC @10794

COPY_EXISTING ~00SWDS97.itm~ ~override~
	SAY IDENTIFIED_DESC @10800

COPY_EXISTING ~00SWDS98.itm~ ~override~
	SAY NAME2 @10801
	SAY IDENTIFIED_DESC @10802

COPY_EXISTING ~00SWDS99.itm~ ~override~
	SAY IDENTIFIED_DESC @10804

COPY_EXISTING ~00SWDSLS.itm~ ~override~
	SAY NAME2 @10805
	SAY IDENTIFIED_DESC @10806

COPY_EXISTING ~00HFSSLS.itm~ ~override~
	SAY NAME2 @10807
	SAY IDENTIFIED_DESC @10808

COPY_EXISTING ~00SWDSSK.itm~ ~override~
	SAY NAME2 @10809
	SAY IDENTIFIED_DESC @10810

COPY_EXISTING ~00HFSSSK.itm~ ~override~
	SAY NAME2 @10811
	SAY IDENTIFIED_DESC @10812

COPY_EXISTING ~00SWDSTD.itm~ ~override~
	SAY NAME2 @10813
	SAY IDENTIFIED_DESC @10814

COPY_EXISTING ~00HFSSTD.itm~ ~override~
	SAY NAME2 @10815
	SAY IDENTIFIED_DESC @10816

COPY_EXISTING ~ZZ35LS.itm~ ~override~
	SAY NAME2 @10817
	SAY IDENTIFIED_DESC @10818

COPY_EXISTING ~ZZ36LS.itm~ ~override~
	SAY NAME2 @10819
	SAY IDENTIFIED_DESC @10820

COPY_EXISTING ~00SWDL07.itm~ ~override~
	SAY NAME2 @10829
	SAY IDENTIFIED_DESC @10830

COPY_EXISTING ~00SWDL09.itm~ ~override~
	SAY IDENTIFIED_DESC @10834

COPY_EXISTING ~00SWDL80.itm~ ~override~
	SAY IDENTIFIED_DESC @10838

COPY_EXISTING ~00SWDL81.itm~ ~override~
	SAY IDENTIFIED_DESC @10840

COPY_EXISTING ~00SWDL82.itm~ ~override~
	SAY IDENTIFIED_DESC @10842

COPY_EXISTING ~00SWDL84.itm~ ~override~
	SAY NAME2 @10845
	SAY IDENTIFIED_DESC @10846

COPY_EXISTING ~00SWDL85.itm~ ~override~
	SAY IDENTIFIED_DESC @10848

COPY_EXISTING ~00SWDL89.itm~ ~override~
	SAY NAME2 @10855
	SAY IDENTIFIED_DESC @10856

COPY_EXISTING ~00SWDL90.itm~ ~override~
	SAY IDENTIFIED_DESC @10858

COPY_EXISTING ~00SWDL91.itm~ ~override~
	SAY IDENTIFIED_DESC @10860

COPY_EXISTING ~00SWDL92.itm~ ~override~
	SAY IDENTIFIED_DESC @10862

COPY_EXISTING ~00SWDL93.itm~ ~override~
	SAY IDENTIFIED_DESC @10864

COPY_EXISTING ~00SWDL94.itm~ ~override~
	SAY IDENTIFIED_DESC @10866

COPY_EXISTING ~00SWDL95.itm~ ~override~
	SAY NAME2 @10867
	SAY IDENTIFIED_DESC @10868

COPY_EXISTING ~00SWDL96.itm~ ~override~
	SAY IDENTIFIED_DESC @10870

COPY_EXISTING ~00SWDL97.itm~ ~override~
	SAY IDENTIFIED_DESC @10872

COPY_EXISTING ~00SWDL98.itm~ ~override~
	SAY IDENTIFIED_DESC @10874

COPY_EXISTING ~00SWDL99.itm~ ~override~
	SAY IDENTIFIED_DESC @10876

COPY_EXISTING ~00SWDLDB.itm~ ~override~
	SAY IDENTIFIED_DESC @10878

COPY_EXISTING ~00HFSLDB.itm~ ~override~
	SAY IDENTIFIED_DESC @10880

COPY_EXISTING ~00SWDLDY.itm~ ~override~
	SAY IDENTIFIED_DESC @10882

COPY_EXISTING ~00HFSLDY.itm~ ~override~
	SAY IDENTIFIED_DESC @10884

COPY_EXISTING ~11SWDLHE.itm~ ~override~
	SAY IDENTIFIED_DESC @10886

COPY_EXISTING ~11HFSLHE.itm~ ~override~
	SAY IDENTIFIED_DESC @10888

COPY_EXISTING ~50SWDLWB.itm~ ~override~
	SAY IDENTIFIED_DESC @10890

COPY_EXISTING ~50HFSLWB.itm~ ~override~
	SAY IDENTIFIED_DESC @10892

COPY_EXISTING ~60SWDLHA.itm~ ~override~
	SAY IDENTIFIED_DESC @10894

COPY_EXISTING ~60HFSLHA.itm~ ~override~
	SAY IDENTIFIED_DESC @10896

COPY_EXISTING ~00SWDB93.itm~ ~override~
	SAY NAME2 @10915
	SAY IDENTIFIED_DESC @10916

COPY_EXISTING ~00SWDB94.itm~ ~override~
	SAY IDENTIFIED_DESC @10918

COPY_EXISTING ~00SWDB95.itm~ ~override~
	SAY NAME2 @10919
	SAY IDENTIFIED_DESC @10920

COPY_EXISTING ~00SWDB96.itm~ ~override~
	SAY IDENTIFIED_DESC @10922

COPY_EXISTING ~00SWDB97.itm~ ~override~
	SAY IDENTIFIED_DESC @10924

COPY_EXISTING ~00SWDB98.itm~ ~override~
	SAY NAME2 @10925
	SAY IDENTIFIED_DESC @10926

COPY_EXISTING ~00SWDB99.itm~ ~override~
	SAY IDENTIFIED_DESC @10928

COPY_EXISTING ~00SWDBBS.itm~ ~override~
	SAY NAME2 @10931
	SAY IDENTIFIED_DESC @10932

COPY_EXISTING ~00HFSBBS.itm~ ~override~
	SAY NAME2 @10933
	SAY IDENTIFIED_DESC @10934

COPY_EXISTING ~00SWDBRC.itm~ ~override~
	SAY NAME2 @10935
	SAY IDENTIFIED_DESC @10936

COPY_EXISTING ~00HFSBRC.itm~ ~override~
	SAY NAME2 @10937
	SAY IDENTIFIED_DESC @10938

COPY_EXISTING ~00SWDBWR.itm~ ~override~
	SAY NAME2 @10939
	SAY IDENTIFIED_DESC @10940

COPY_EXISTING ~00HFSBWR.itm~ ~override~
	SAY NAME2 @10941
	SAY IDENTIFIED_DESC @10942

COPY_EXISTING ~00SWDC87.itm~ ~override~
	SAY NAME2 @10945
	SAY IDENTIFIED_DESC @10946

COPY_EXISTING ~00SWDC88.itm~ ~override~
	SAY NAME2 @10947
	SAY IDENTIFIED_DESC @10948

COPY_EXISTING ~00SWDC89.itm~ ~override~
	SAY IDENTIFIED_DESC @10950

COPY_EXISTING ~00SWDC90.itm~ ~override~
	SAY IDENTIFIED_DESC @10952

COPY_EXISTING ~00SWDC91.itm~ ~override~
	SAY NAME2 @10953
	SAY IDENTIFIED_DESC @10954

COPY_EXISTING ~00SWDC92.itm~ ~override~
	SAY IDENTIFIED_DESC @10956

COPY_EXISTING ~00SWDC93.itm~ ~override~
	SAY NAME2 @10957
	SAY IDENTIFIED_DESC @10958

COPY_EXISTING ~00SWDCCS.itm~ ~override~
	SAY NAME2 @10971
	SAY IDENTIFIED_DESC @10972

COPY_EXISTING ~00HFSCCS.itm~ ~override~
	SAY NAME2 @10973
	SAY IDENTIFIED_DESC @10974

COPY_EXISTING ~63SWDCSS.itm~ ~override~
	SAY NAME2 @10975
	SAY IDENTIFIED_DESC @10976

COPY_EXISTING ~63HFSCSS.itm~ ~override~
	SAY NAME2 @10977
	SAY IDENTIFIED_DESC @10978

COPY_EXISTING ~00SWDT90.itm~ ~override~
	SAY IDENTIFIED_DESC @10994

COPY_EXISTING ~00SWDT93.itm~ ~override~
	SAY IDENTIFIED_DESC @11000

COPY_EXISTING ~USHFST93.itm~ ~override~
	SAY NAME2 @11001
	SAY IDENTIFIED_DESC @11002

COPY_EXISTING ~00SWDT94.itm~ ~override~
	SAY IDENTIFIED_DESC @11004

COPY_EXISTING ~00SWDT97.itm~ ~override~
	SAY IDENTIFIED_DESC @11010

COPY_EXISTING ~00SWDT99.itm~ ~override~
	SAY IDENTIFIED_DESC @11014

COPY_EXISTING ~00SWDTCL.itm~ ~override~
	SAY NAME2 @11015

COPY_EXISTING ~00HFSTCL.itm~ ~override~
	SAY NAME2 @11017

COPY_EXISTING ~11SWDTWS.itm~ ~override~
	SAY IDENTIFIED_DESC @11020

COPY_EXISTING ~00STAF80.itm~ ~override~
	SAY NAME2 @11039
	SAY IDENTIFIED_DESC @11040

COPY_EXISTING ~00STAF81.itm~ ~override~
	SAY IDENTIFIED_DESC @11042

COPY_EXISTING ~00STAF82.itm~ ~override~
	SAY IDENTIFIED_DESC @11044

COPY_EXISTING ~00STAF83.itm~ ~override~
	SAY IDENTIFIED_DESC @11046

COPY_EXISTING ~00STAF84.itm~ ~override~
	SAY IDENTIFIED_DESC @11048

COPY_EXISTING ~00STAF85.itm~ ~override~
	SAY IDENTIFIED_DESC @11050

COPY_EXISTING ~00STAF86.itm~ ~override~
	SAY NAME2 @11051

COPY_EXISTING ~00STAF87.itm~ ~override~
	SAY IDENTIFIED_DESC @11054

COPY_EXISTING ~00STAF89.itm~ ~override~
	SAY NAME2 @11057
	SAY IDENTIFIED_DESC @11058

COPY_EXISTING ~00STAF90.itm~ ~override~
	SAY IDENTIFIED_DESC @11060

COPY_EXISTING ~00STAF91.itm~ ~override~
	SAY NAME2 @11061
	SAY IDENTIFIED_DESC @11062

COPY_EXISTING ~00STAF92.itm~ ~override~
	SAY NAME2 @11063
	SAY IDENTIFIED_DESC @11064

COPY_EXISTING ~00STAF93.itm~ ~override~
	SAY NAME2 @11065
	SAY IDENTIFIED_DESC @11066

COPY_EXISTING ~00STAFDD.itm~ ~override~
	SAY IDENTIFIED_DESC @11080

COPY_EXISTING ~00HFSFDD.itm~ ~override~
	SAY NAME2 @11081
	SAY IDENTIFIED_DESC @11082

COPY_EXISTING ~11HFSFPI.itm~ ~override~
	SAY IDENTIFIED_DESC @11086

COPY_EXISTING ~12HFSFWS.itm~ ~override~
	SAY IDENTIFIED_DESC @11090

COPY_EXISTING ~51STAFRH.itm~ ~override~
	SAY IDENTIFIED_DESC @11092

COPY_EXISTING ~51HFSFRH.itm~ ~override~
	SAY IDENTIFIED_DESC @11094

COPY_EXISTING ~00SPER08.itm~ ~override~
	SAY NAME2 @11099
	SAY IDENTIFIED_DESC @11100

COPY_EXISTING ~USHFSR08.itm~ ~override~
	SAY NAME2 @11101
	SAY IDENTIFIED_DESC @11102

COPY_EXISTING ~00SPER89.itm~ ~override~
	SAY IDENTIFIED_DESC @11104

COPY_EXISTING ~00SPER90.itm~ ~override~
	SAY IDENTIFIED_DESC @11106

COPY_EXISTING ~00SPER93.itm~ ~override~
	SAY IDENTIFIED_DESC @11112

COPY_EXISTING ~00SPER94.itm~ ~override~
	SAY IDENTIFIED_DESC @11114

COPY_EXISTING ~00SPERIM.itm~ ~override~
	SAY NAME2 @11125
	SAY IDENTIFIED_DESC @11126

COPY_EXISTING ~00HFSRIM.itm~ ~override~
	SAY NAME2 @11127
	SAY IDENTIFIED_DESC @11128

COPY_EXISTING ~11HFSRNP.itm~ ~override~
	SAY IDENTIFIED_DESC @11132

COPY_EXISTING ~50SPERKS.itm~ ~override~
	SAY IDENTIFIED_DESC @11134

COPY_EXISTING ~50HFSRKS.itm~ ~override~
	SAY IDENTIFIED_DESC @11136

COPY_EXISTING ~00HALB92.itm~ ~override~
	SAY IDENTIFIED_DESC @11154

COPY_EXISTING ~00HALB93.itm~ ~override~
	SAY IDENTIFIED_DESC @11156

COPY_EXISTING ~00HALB95.itm~ ~override~
	SAY IDENTIFIED_DESC @11160

COPY_EXISTING ~00HALB96.itm~ ~override~
	SAY NAME2 @11161
	SAY IDENTIFIED_DESC @11162

COPY_EXISTING ~00HALB98.itm~ ~override~
	SAY NAME2 @11165
	SAY IDENTIFIED_DESC @11166

COPY_EXISTING ~00HALB99.itm~ ~override~
	SAY IDENTIFIED_DESC @11168

COPY_EXISTING ~00HALBDC.itm~ ~override~
	SAY NAME2 @11169
	SAY IDENTIFIED_DESC @11170

COPY_EXISTING ~00HFHBDC.itm~ ~override~
	SAY NAME2 @11171
	SAY IDENTIFIED_DESC @11172

COPY_EXISTING ~00HALBHL.itm~ ~override~
	SAY NAME2 @11173
	SAY IDENTIFIED_DESC @11174

COPY_EXISTING ~00HFHBHL.itm~ ~override~
	SAY NAME2 @11175
	SAY IDENTIFIED_DESC @11176

COPY_EXISTING ~00AX1H73.itm~ ~override~
	SAY NAME2 @11195
	SAY IDENTIFIED_DESC @11196

COPY_EXISTING ~00AX1H74.itm~ ~override~
	SAY IDENTIFIED_DESC @11198

COPY_EXISTING ~00AX1H75.itm~ ~override~
	SAY IDENTIFIED_DESC @11200

COPY_EXISTING ~00AX1H81.itm~ ~override~
	SAY NAME2 @11211
	SAY IDENTIFIED_DESC @11212

COPY_EXISTING ~00AX1H82.itm~ ~override~
	SAY IDENTIFIED_DESC @11214

COPY_EXISTING ~00AX1H83.itm~ ~override~
	SAY IDENTIFIED_DESC @11216

COPY_EXISTING ~00AX1H84.itm~ ~override~
	SAY NAME2 @11217
	SAY IDENTIFIED_DESC @11218

COPY_EXISTING ~00AX1H85.itm~ ~override~
	SAY IDENTIFIED_DESC @11220

COPY_EXISTING ~00AX1H86.itm~ ~override~
	SAY NAME2 @11221
	SAY IDENTIFIED_DESC @11222

COPY_EXISTING ~00AX1H87.itm~ ~override~
	SAY NAME2 @11223
	SAY IDENTIFIED_DESC @11224

COPY_EXISTING ~00AX1H88.itm~ ~override~
	SAY IDENTIFIED_DESC @11226

COPY_EXISTING ~00AX1H90.itm~ ~override~
	SAY NAME2 @11229
	SAY IDENTIFIED_DESC @11230

COPY_EXISTING ~00AX1H94.itm~ ~override~
	SAY NAME2 @11237

COPY_EXISTING ~00AX1H97.itm~ ~override~
	SAY NAME2 @11243
	SAY IDENTIFIED_DESC @11244

COPY_EXISTING ~00AX1H98.itm~ ~override~
	SAY NAME2 @11245
	SAY IDENTIFIED_DESC @11246

COPY_EXISTING ~00AX1H99.itm~ ~override~
	SAY NAME2 @11247
	SAY IDENTIFIED_DESC @11248

COPY_EXISTING ~00AX1HAS.itm~ ~override~
	SAY NAME2 @11249
	SAY IDENTIFIED_DESC @11250

COPY_EXISTING ~00HFAXAS.itm~ ~override~
	SAY NAME2 @11251
	SAY IDENTIFIED_DESC @11252

COPY_EXISTING ~00AX1HCK.itm~ ~override~
	SAY NAME2 @11257
	SAY IDENTIFIED_DESC @11258

COPY_EXISTING ~00HFAXCK.itm~ ~override~
	SAY NAME2 @11259
	SAY IDENTIFIED_DESC @11260

COPY_EXISTING ~00AX1HSC.itm~ ~override~
	SAY NAME2 @11261
	SAY IDENTIFIED_DESC @11262

COPY_EXISTING ~00HFAXSC.itm~ ~override~
	SAY NAME2 @11263
	SAY IDENTIFIED_DESC @11264

COPY_EXISTING ~00AX1HSP.itm~ ~override~
	SAY NAME2 @11265
	SAY IDENTIFIED_DESC @11266

COPY_EXISTING ~00HFAXSP.itm~ ~override~
	SAY NAME2 @11267
	SAY IDENTIFIED_DESC @11268

COPY_EXISTING ~00AX1HTA.itm~ ~override~
	SAY NAME2 @11269

COPY_EXISTING ~11AX1HHO.itm~ ~override~
	SAY NAME2 @11271

COPY_EXISTING ~11HFAXHO.itm~ ~override~
	SAY NAME2 @11273
	SAY IDENTIFIED_DESC @11274

COPY_EXISTING ~11AX1HKS.itm~ ~override~
	SAY IDENTIFIED_DESC @11276

COPY_EXISTING ~11HFAXKS.itm~ ~override~
	SAY IDENTIFIED_DESC @11278

COPY_EXISTING ~41AX1HAI.itm~ ~override~
	SAY IDENTIFIED_DESC @11280

COPY_EXISTING ~USHFAXAI.itm~ ~override~
	SAY IDENTIFIED_DESC @11282

COPY_EXISTING ~51AX1HDF.itm~ ~override~
	SAY NAME2 @11283
	SAY IDENTIFIED_DESC @11284

COPY_EXISTING ~51HFAXDF.itm~ ~override~
	SAY NAME2 @11285
	SAY IDENTIFIED_DESC @11286

COPY_EXISTING ~ZZI6SC.itm~ ~override~
	SAY NAME2 @11287
	PATCH_IF (MOD_IS_INSTALLED ~iwd2ee.tp2~ ~24~) BEGIN //If Better Racial Enemies is installed
		SAY IDENTIFIED_DESC @11290
	END 

COPY_EXISTING ~ZZI6HFSC.itm~ ~override~
	SAY NAME2 @11291
	PATCH_IF (MOD_IS_INSTALLED ~iwd2ee.tp2~ ~24~) BEGIN //If Better Racial Enemies is installed
		SAY IDENTIFIED_DESC @11294
	END 

COPY_EXISTING ~00AX2H85.itm~ ~override~
	SAY NAME2 @11297
	SAY IDENTIFIED_DESC @11298

COPY_EXISTING ~00AX2H86.itm~ ~override~
	SAY NAME2 @11299
	SAY IDENTIFIED_DESC @11300

COPY_EXISTING ~00AX2H87.itm~ ~override~
	SAY IDENTIFIED_DESC @11302

COPY_EXISTING ~00AX2H93.itm~ ~override~
	SAY IDENTIFIED_DESC @11314

COPY_EXISTING ~00AX2H94.itm~ ~override~
	SAY NAME2 @11315
	SAY IDENTIFIED_DESC @11316

COPY_EXISTING ~00AX2H95.itm~ ~override~
	SAY NAME2 @11317
	SAY IDENTIFIED_DESC @11318

COPY_EXISTING ~00AX2H96.itm~ ~override~
	SAY NAME2 @11319
	SAY IDENTIFIED_DESC @11320

COPY_EXISTING ~00AX2H98.itm~ ~override~
	SAY NAME2 @11323
	SAY IDENTIFIED_DESC @11324

COPY_EXISTING ~00AX2H99.itm~ ~override~
	SAY NAME2 @11325
	SAY IDENTIFIED_DESC @11326

COPY_EXISTING ~00AX2HBB.itm~ ~override~
	SAY NAME2 @11327
	SAY IDENTIFIED_DESC @11328

COPY_EXISTING ~00HFAXBB.itm~ ~override~
	SAY NAME2 @11329
	SAY IDENTIFIED_DESC @11330

COPY_EXISTING ~00AX2HBD.itm~ ~override~
	SAY NAME2 @11331
	SAY IDENTIFIED_DESC @11332

COPY_EXISTING ~00HFAXBD.itm~ ~override~
	SAY NAME2 @11333
	SAY IDENTIFIED_DESC @11334

COPY_EXISTING ~00AX2HWT.itm~ ~override~
	SAY NAME2 @11335

COPY_EXISTING ~00HFAXWT.itm~ ~override~
	SAY NAME2 @11337

COPY_EXISTING ~11HFAXEW.itm~ ~override~
	SAY IDENTIFIED_DESC @11342

COPY_EXISTING ~00CLUB82.itm~ ~override~
	SAY IDENTIFIED_DESC @11348

COPY_EXISTING ~00CLUB84.itm~ ~override~
	SAY NAME2 @11351
	SAY IDENTIFIED_DESC @11352

COPY_EXISTING ~00CLUB86.itm~ ~override~
	SAY NAME2 @11355
	SAY IDENTIFIED_DESC @11356

COPY_EXISTING ~00CLUB87.itm~ ~override~
	SAY IDENTIFIED_DESC @11358

COPY_EXISTING ~00CLUB88.itm~ ~override~
	SAY IDENTIFIED_DESC @11360

COPY_EXISTING ~00CLUB89.itm~ ~override~
	SAY IDENTIFIED_DESC @11362

COPY_EXISTING ~00CLUB90.itm~ ~override~
	SAY IDENTIFIED_DESC @11364

COPY_EXISTING ~00CLUB92.itm~ ~override~
	SAY NAME2 @11367
	SAY IDENTIFIED_DESC @11368

COPY_EXISTING ~00CLUB95.itm~ ~override~
	SAY NAME2 @11373
	SAY IDENTIFIED_DESC @11374

COPY_EXISTING ~00CLUB96.itm~ ~override~
	SAY NAME2 @11375
	SAY IDENTIFIED_DESC @11376

COPY_EXISTING ~00CLUBHK.itm~ ~override~
	SAY NAME2 @11383
	SAY IDENTIFIED_DESC @11384

COPY_EXISTING ~00HFCBHK.itm~ ~override~
	SAY NAME2 @11385
	SAY IDENTIFIED_DESC @11386

COPY_EXISTING ~ZZG6CT.itm~ ~override~
	SAY IDENTIFIED_DESC @11388

COPY_EXISTING ~11HFCBMK.itm~ ~override~
	SAY IDENTIFIED_DESC @11392

COPY_EXISTING ~50HFCLBT.itm~ ~override~
	SAY IDENTIFIED_DESC @11396

COPY_EXISTING ~63CLUBMP.itm~ ~override~
	SAY IDENTIFIED_DESC @11398

COPY_EXISTING ~63HFCBMP.itm~ ~override~
	SAY IDENTIFIED_DESC @11400

COPY_EXISTING ~00MACE89.itm~ ~override~
	SAY NAME2 @11407
	SAY IDENTIFIED_DESC @11408

COPY_EXISTING ~00MACE92.itm~ ~override~
	SAY NAME2 @11413
	SAY IDENTIFIED_DESC @11414

COPY_EXISTING ~00MACE93.itm~ ~override~
	SAY NAME2 @11415
	SAY IDENTIFIED_DESC @11416

COPY_EXISTING ~00MACE94.itm~ ~override~
	SAY NAME2 @11417
	SAY IDENTIFIED_DESC @11418

COPY_EXISTING ~00MACE95.itm~ ~override~
	SAY NAME2 @11419
	SAY IDENTIFIED_DESC @11420

COPY_EXISTING ~00MACEAR.itm~ ~override~
	SAY NAME2 @11429
	SAY IDENTIFIED_DESC @11430

COPY_EXISTING ~00HFMEAR.itm~ ~override~
	SAY NAME2 @11431
	SAY IDENTIFIED_DESC @11432

COPY_EXISTING ~00MACECF.itm~ ~override~
	SAY NAME2 @11433

COPY_EXISTING ~00HFMECF.itm~ ~override~
	SAY NAME2 @11435

COPY_EXISTING ~ZZJ6MM.itm~ ~override~
	SAY IDENTIFIED_DESC @11438

COPY_EXISTING ~ZZJ6HFMM.itm~ ~override~
	SAY IDENTIFIED_DESC @11440

COPY_EXISTING ~00MSTR85.itm~ ~override~
	SAY IDENTIFIED_DESC @11450

COPY_EXISTING ~00MSTR91.itm~ ~override~
	SAY NAME2 @11461
	SAY IDENTIFIED_DESC @11462

COPY_EXISTING ~00MSTR92.itm~ ~override~
	SAY NAME2 @11463
	SAY IDENTIFIED_DESC @11464

COPY_EXISTING ~00MSTR93.itm~ ~override~
	SAY IDENTIFIED_DESC @11466

COPY_EXISTING ~00MSTR95.itm~ ~override~
	SAY IDENTIFIED_DESC @11470

COPY_EXISTING ~00MSTR97.itm~ ~override~
	SAY IDENTIFIED_DESC @11474

COPY_EXISTING ~00MSTRMG.itm~ ~override~
	SAY NAME2 @11479
	SAY IDENTIFIED_DESC @11480

COPY_EXISTING ~00HFMRMG.itm~ ~override~
	SAY NAME2 @11481
	SAY IDENTIFIED_DESC @11482

COPY_EXISTING ~00MSTRMS.itm~ ~override~
	SAY NAME2 @11483
	SAY IDENTIFIED_DESC @11484

COPY_EXISTING ~00HFMRMS.itm~ ~override~
	SAY NAME2 @11485
	SAY IDENTIFIED_DESC @11486

COPY_EXISTING ~00FLAL03.itm~ ~override~
	SAY NAME2 @11491
	SAY IDENTIFIED_DESC @11492

COPY_EXISTING ~USHFFL03.itm~ ~override~
	SAY NAME2 @11493
	SAY IDENTIFIED_DESC @11494

COPY_EXISTING ~00FLAL85.itm~ ~override~
	SAY IDENTIFIED_DESC @11496

COPY_EXISTING ~00FLAL87.itm~ ~override~
	SAY IDENTIFIED_DESC @11500

COPY_EXISTING ~00FLAL88.itm~ ~override~
	SAY IDENTIFIED_DESC @11502

COPY_EXISTING ~00FLAL90.itm~ ~override~
	SAY NAME2 @11505
	SAY IDENTIFIED_DESC @11506

COPY_EXISTING ~00FLAL95.itm~ ~override~
	SAY NAME2 @11515
	SAY IDENTIFIED_DESC @11516

COPY_EXISTING ~00FLAL96.itm~ ~override~
	SAY NAME2 @11517
	SAY IDENTIFIED_DESC @11518

COPY_EXISTING ~00FLAL98.itm~ ~override~
	SAY NAME2 @11521
	SAY IDENTIFIED_DESC @11522

COPY_EXISTING ~00FLALFV.itm~ ~override~
	SAY NAME2 @11525
	SAY IDENTIFIED_DESC @11526

COPY_EXISTING ~00HFFLFV.itm~ ~override~
	SAY NAME2 @11527
	SAY IDENTIFIED_DESC @11528

COPY_EXISTING ~00FLALSR.itm~ ~override~
	SAY NAME2 @11529
	SAY IDENTIFIED_DESC @11530

COPY_EXISTING ~00HFFLSR.itm~ ~override~
	SAY NAME2 @11531
	SAY IDENTIFIED_DESC @11532

COPY_EXISTING ~00MSTRSS.itm~ ~override~
	SAY NAME2 @11533
	SAY IDENTIFIED_DESC @11534

COPY_EXISTING ~00HFMRSS.itm~ ~override~
	SAY NAME2 @11535
	SAY IDENTIFIED_DESC @11536

COPY_EXISTING ~11FLALBC.itm~ ~override~
	SAY IDENTIFIED_DESC @11538

COPY_EXISTING ~11HFFLBC.itm~ ~override~
	SAY IDENTIFIED_DESC @11540

COPY_EXISTING ~63FLALPF.itm~ ~override~
	SAY IDENTIFIED_DESC @11542

COPY_EXISTING ~63HFFLPF.itm~ ~override~
	SAY IDENTIFIED_DESC @11544

COPY_EXISTING ~00HAMM88.itm~ ~override~
	SAY IDENTIFIED_DESC @11560

COPY_EXISTING ~00HAMM89.itm~ ~override~
	SAY IDENTIFIED_DESC @11562

COPY_EXISTING ~00HAMM90.itm~ ~override~
	SAY IDENTIFIED_DESC @11564

COPY_EXISTING ~00HAMM91.itm~ ~override~
	SAY NAME2 @11565
	SAY IDENTIFIED_DESC @11566

COPY_EXISTING ~00HAMM92.itm~ ~override~
	SAY NAME2 @11567
	SAY IDENTIFIED_DESC @11568

COPY_EXISTING ~00HAMM95.itm~ ~override~
	SAY NAME2 @11573
	SAY IDENTIFIED_DESC @11574

COPY_EXISTING ~00HAMM96.itm~ ~override~
	SAY NAME2 @11575
	SAY IDENTIFIED_DESC @11576

COPY_EXISTING ~00HAMM97.itm~ ~override~
	SAY NAME2 @11577
	SAY IDENTIFIED_DESC @11578

COPY_EXISTING ~00HAMM98.itm~ ~override~
	SAY IDENTIFIED_DESC @11580

COPY_EXISTING ~00HAMMPH.itm~ ~override~
	SAY NAME2 @11583
	SAY IDENTIFIED_DESC @11584

COPY_EXISTING ~00HFHMPH.itm~ ~override~
	SAY NAME2 @11585
	SAY IDENTIFIED_DESC @11586

COPY_EXISTING ~00HAMMSC.itm~ ~override~
	SAY NAME2 @11587
	SAY IDENTIFIED_DESC @11588

COPY_EXISTING ~00HFHRSC.itm~ ~override~
	SAY NAME2 @11589
	SAY IDENTIFIED_DESC @11590

COPY_EXISTING ~11HFHRCR.itm~ ~override~
	SAY IDENTIFIED_DESC @11594

COPY_EXISTING ~51HAMMDA.itm~ ~override~
	SAY IDENTIFIED_DESC @11596

COPY_EXISTING ~51HFHRDA.itm~ ~override~
	SAY IDENTIFIED_DESC @11598

COPY_EXISTING ~51HAMMVA.itm~ ~override~
	SAY IDENTIFIED_DESC @11600

COPY_EXISTING ~51HFHRVA.itm~ ~override~
	SAY IDENTIFIED_DESC @11602

COPY_EXISTING ~63HAMMBI.itm~ ~override~
	SAY IDENTIFIED_DESC @11604

COPY_EXISTING ~63HFHRBI.itm~ ~override~
	SAY IDENTIFIED_DESC @11606


COPY_EXISTING ~00DART03.itm~ ~override~
	SAY IDENTIFIED_DESC @11632

COPY_EXISTING ~00DART04.itm~ ~override~
	SAY IDENTIFIED_DESC @11634

COPY_EXISTING ~00DART05.itm~ ~override~
	SAY NAME2 @11635
	SAY IDENTIFIED_DESC @11636

COPY_EXISTING ~00DART83.itm~ ~override~
	SAY IDENTIFIED_DESC @11638

COPY_EXISTING ~00DART84.itm~ ~override~
	SAY IDENTIFIED_DESC @11640

COPY_EXISTING ~00DART85.itm~ ~override~
	SAY IDENTIFIED_DESC @11642

COPY_EXISTING ~00DART86.itm~ ~override~
	SAY IDENTIFIED_DESC @11644

COPY_EXISTING ~00DART87.itm~ ~override~
	SAY NAME2 @11645
	SAY IDENTIFIED_DESC @11646

COPY_EXISTING ~00DART88.itm~ ~override~
	SAY NAME2 @11647

COPY_EXISTING ~00DART94.itm~ ~override~
	SAY NAME2 @11659
	SAY IDENTIFIED_DESC @11660

COPY_EXISTING ~00DART95.itm~ ~override~
	SAY NAME2 @11661

COPY_EXISTING ~00DART96.itm~ ~override~
	SAY NAME2 @11663
	SAY IDENTIFIED_DESC @11664

COPY_EXISTING ~00DART97.itm~ ~override~
	SAY NAME2 @11665

COPY_EXISTING ~00DART98.itm~ ~override~
	SAY NAME2 @11667
	SAY IDENTIFIED_DESC @11668

COPY_EXISTING ~00DART99.itm~ ~override~
	SAY NAME2 @11669
	SAY IDENTIFIED_DESC @11670

COPY_EXISTING ~00DARTAT.itm~ ~override~
	SAY NAME2 @11671
	SAY IDENTIFIED_DESC @11672

COPY_EXISTING ~00HFDTAT.itm~ ~override~
	SAY NAME2 @11673
	SAY IDENTIFIED_DESC @11674

COPY_EXISTING ~00DARTDD.itm~ ~override~
	SAY NAME2 @11675
	SAY IDENTIFIED_DESC @11676

COPY_EXISTING ~00HFDTDD.itm~ ~override~
	SAY NAME2 @11677
	SAY IDENTIFIED_DESC @11678

COPY_EXISTING ~00DARTPD.itm~ ~override~
	SAY NAME2 @11679

COPY_EXISTING ~00HFDTPD.itm~ ~override~
	SAY NAME2 @11681


COPY_EXISTING ~00BOWS86.itm~ ~override~
	SAY NAME2 @11689
	SAY IDENTIFIED_DESC @11690

COPY_EXISTING ~00BOWS87.itm~ ~override~
	SAY NAME2 @11691
	SAY IDENTIFIED_DESC @11692

COPY_EXISTING ~00BOWS88.itm~ ~override~
	SAY NAME2 @11693
	SAY IDENTIFIED_DESC @11694

COPY_EXISTING ~00BOWS89.itm~ ~override~
	SAY NAME2 @11695
	SAY IDENTIFIED_DESC @11696

COPY_EXISTING ~00BOWS90.itm~ ~override~
	SAY IDENTIFIED_DESC @11698

COPY_EXISTING ~00BOWS91.itm~ ~override~
	SAY NAME2 @11699
	SAY IDENTIFIED_DESC @11700

COPY_EXISTING ~00BOWS92.itm~ ~override~
	SAY NAME2 @11701
	SAY IDENTIFIED_DESC @11702

COPY_EXISTING ~00BOWS93.itm~ ~override~
	SAY NAME2 @11703
	SAY IDENTIFIED_DESC @11704

COPY_EXISTING ~00BOWS94.itm~ ~override~
	SAY NAME2 @11705
	SAY IDENTIFIED_DESC @11706

COPY_EXISTING ~00BOWS95.itm~ ~override~
	SAY IDENTIFIED_DESC @11708


COPY_EXISTING ~00BOWSEH.itm~ ~override~
	SAY NAME2 @11717
	SAY IDENTIFIED_DESC @11718

COPY_EXISTING ~00HFBSEH.itm~ ~override~
	SAY NAME2 @11719
	SAY IDENTIFIED_DESC @11720

COPY_EXISTING ~00BOWSRS.itm~ ~override~
	SAY NAME2 @11721
	SAY IDENTIFIED_DESC @11722

COPY_EXISTING ~00HFBSRS.itm~ ~override~
	SAY NAME2 @11723
	SAY IDENTIFIED_DESC @11724


COPY_EXISTING ~00BOWP97.itm~ ~override~
	SAY NAME2 @11729
	SAY IDENTIFIED_DESC @11730

COPY_EXISTING ~00BOWP98.itm~ ~override~
	SAY IDENTIFIED_DESC @11732

COPY_EXISTING ~00BOWP99.itm~ ~override~
	SAY NAME2 @11733
	SAY IDENTIFIED_DESC @11734


COPY_EXISTING ~00BOWL95.itm~ ~override~
	SAY IDENTIFIED_DESC @11750

COPY_EXISTING ~00BOWL96.itm~ ~override~
	SAY NAME2 @11751
	SAY IDENTIFIED_DESC @11752

COPY_EXISTING ~00BOWL97.itm~ ~override~
	SAY NAME2 @11753
	SAY IDENTIFIED_DESC @11754

COPY_EXISTING ~00BOWL98.itm~ ~override~
	SAY NAME2 @11755
	SAY IDENTIFIED_DESC @11756

COPY_EXISTING ~00BOWL99.itm~ ~override~
	SAY NAME2 @11757
	SAY IDENTIFIED_DESC @11758

COPY_EXISTING ~00BOWLFK.itm~ ~override~
	SAY NAME2 @11759
	SAY IDENTIFIED_DESC @11760

COPY_EXISTING ~00HFBLFK.itm~ ~override~
	SAY NAME2 @11761
	SAY IDENTIFIED_DESC @11762

COPY_EXISTING ~00BOWLSF.itm~ ~override~
	SAY NAME2 @11763

COPY_EXISTING ~00HFBLSF.itm~ ~override~
	SAY NAME2 @11765

COPY_EXISTING ~00BOWLSR.itm~ ~override~
	SAY NAME2 @11767
	SAY IDENTIFIED_DESC @11768

COPY_EXISTING ~00HFBLSR.itm~ ~override~
	SAY NAME2 @11769
	SAY IDENTIFIED_DESC @11770


COPY_EXISTING ~00BOWC92.itm~ ~override~
	SAY NAME2 @11777
	SAY IDENTIFIED_DESC @11778

COPY_EXISTING ~00BOWC93.itm~ ~override~
	SAY NAME2 @11779
	SAY IDENTIFIED_DESC @11780

COPY_EXISTING ~00BOWC94.itm~ ~override~
	SAY NAME2 @11781
	SAY IDENTIFIED_DESC @11782

COPY_EXISTING ~00BOWC95.itm~ ~override~
	SAY NAME2 @11783
	SAY IDENTIFIED_DESC @11784


COPY_EXISTING ~00BOWCAG.itm~ ~override~
	SAY NAME2 @11793
	SAY IDENTIFIED_DESC @11794

COPY_EXISTING ~00HFBCAG.itm~ ~override~
	SAY NAME2 @11795
	SAY IDENTIFIED_DESC @11796


COPY_EXISTING ~00BWLX03.itm~ ~override~
	SAY IDENTIFIED_DESC @11802

COPY_EXISTING ~00BWLX04.itm~ ~override~
	SAY IDENTIFIED_DESC @11804

COPY_EXISTING ~00BWLX91.itm~ ~override~
	SAY NAME2 @11805
	SAY IDENTIFIED_DESC @11806

COPY_EXISTING ~00BWLX92.itm~ ~override~
	SAY IDENTIFIED_DESC @11808

COPY_EXISTING ~00BWLX93.itm~ ~override~
	SAY IDENTIFIED_DESC @11810

COPY_EXISTING ~00BWLX94.itm~ ~override~
	SAY IDENTIFIED_DESC @11812

COPY_EXISTING ~00BWLX95.itm~ ~override~
	SAY IDENTIFIED_DESC @11814

COPY_EXISTING ~00BWLX96.itm~ ~override~
	SAY NAME2 @11815
	SAY IDENTIFIED_DESC @11816

COPY_EXISTING ~00BWLX97.itm~ ~override~
	SAY NAME2 @11817
	SAY IDENTIFIED_DESC @11818

COPY_EXISTING ~00BWLX98.itm~ ~override~
	SAY NAME2 @11819
	SAY IDENTIFIED_DESC @11820

COPY_EXISTING ~00BWLX99.itm~ ~override~
	SAY NAME2 @11821

COPY_EXISTING ~00BWLXHF.itm~ ~override~
	SAY NAME2 @11823
	SAY IDENTIFIED_DESC @11824

COPY_EXISTING ~00HFLXHF.itm~ ~override~
	SAY NAME2 @11825
	SAY IDENTIFIED_DESC @11826

COPY_EXISTING ~00BWLXIM.itm~ ~override~
	SAY NAME2 @11827
	SAY IDENTIFIED_DESC @11828

COPY_EXISTING ~00HFLXIM.itm~ ~override~
	SAY NAME2 @11829
	SAY IDENTIFIED_DESC @11830

COPY_EXISTING ~00BWLXMB.itm~ ~override~
	SAY NAME2 @11831
	SAY IDENTIFIED_DESC @11832

COPY_EXISTING ~00HFLXMB.itm~ ~override~
	SAY NAME2 @11833
	SAY IDENTIFIED_DESC @11834


COPY_EXISTING ~00BWHX01.itm~ ~override~
	SAY IDENTIFIED_DESC @11836

COPY_EXISTING ~00BWHX02.itm~ ~override~
	SAY IDENTIFIED_DESC @11838

COPY_EXISTING ~00BWHX03.itm~ ~override~
	SAY IDENTIFIED_DESC @11840

COPY_EXISTING ~00BWHX04.itm~ ~override~
	SAY NAME2 @11841
	SAY IDENTIFIED_DESC @11842

COPY_EXISTING ~00BWHX91.itm~ ~override~
	SAY IDENTIFIED_DESC @11844

COPY_EXISTING ~00BWHX92.itm~ ~override~
	SAY IDENTIFIED_DESC @11846

COPY_EXISTING ~00BWHX93.itm~ ~override~
	SAY IDENTIFIED_DESC @11848

COPY_EXISTING ~00BWHX94.itm~ ~override~
	SAY IDENTIFIED_DESC @11850

COPY_EXISTING ~00BWHX95.itm~ ~override~
	SAY NAME2 @11851
	SAY IDENTIFIED_DESC @11852

COPY_EXISTING ~00BWHX96.itm~ ~override~
	SAY NAME2 @11853
	SAY IDENTIFIED_DESC @11854

COPY_EXISTING ~00BWHX97.itm~ ~override~
	SAY NAME2 @11855
	SAY IDENTIFIED_DESC @11856

COPY_EXISTING ~00BWHX98.itm~ ~override~
	SAY IDENTIFIED_DESC @11858

COPY_EXISTING ~00BWHX99.itm~ ~override~
	SAY NAME2 @11859
	SAY IDENTIFIED_DESC @11860

COPY_EXISTING ~00BWHXGE.itm~ ~override~
	SAY NAME2 @11861
	SAY IDENTIFIED_DESC @11862

COPY_EXISTING ~00HFHXGE.itm~ ~override~
	SAY NAME2 @11863
	SAY IDENTIFIED_DESC @11864

COPY_EXISTING ~00BWHXHF.itm~ ~override~
	SAY NAME2 @11865
	SAY IDENTIFIED_DESC @11866

COPY_EXISTING ~00HFHXHF.itm~ ~override~
	SAY NAME2 @11867
	SAY IDENTIFIED_DESC @11868

COPY_EXISTING ~00BWHXIA.itm~ ~override~
	SAY NAME2 @11869
	SAY IDENTIFIED_DESC @11870

COPY_EXISTING ~00HFHXIA.itm~ ~override~
	SAY NAME2 @11871
	SAY IDENTIFIED_DESC @11872

COPY_EXISTING ~00BWHXMR.itm~ ~override~
	SAY NAME2 @11873
	SAY IDENTIFIED_DESC @11874

COPY_EXISTING ~00HFHXMR.itm~ ~override~
	SAY NAME2 @11875
	SAY IDENTIFIED_DESC @11876

COPY_EXISTING ~51BWHXDB.itm~ ~override~
	SAY IDENTIFIED_DESC @11878

COPY_EXISTING ~51HFHXDB.itm~ ~override~
	SAY IDENTIFIED_DESC @11880

COPY_EXISTING ~51BWHXHB.itm~ ~override~
	SAY IDENTIFIED_DESC @11882

COPY_EXISTING ~51HFHXHB.itm~ ~override~
	SAY IDENTIFIED_DESC @11884


COPY_EXISTING ~00SLNG88.itm~ ~override~
	SAY NAME2 @11889
	SAY IDENTIFIED_DESC @11890

COPY_EXISTING ~00SLNG89.itm~ ~override~
	SAY NAME2 @11891
	SAY IDENTIFIED_DESC @11892


COPY_EXISTING ~00SLNG92.itm~ ~override~
	SAY NAME2 @11897
	SAY IDENTIFIED_DESC @11898

COPY_EXISTING ~00SLNG93.itm~ ~override~
	SAY NAME2 @11899
	SAY IDENTIFIED_DESC @11900

COPY_EXISTING ~00SLNG94.itm~ ~override~
	SAY IDENTIFIED_DESC @11902


COPY_EXISTING ~00SLNGCT.itm~ ~override~
	SAY NAME2 @11913
	SAY IDENTIFIED_DESC @11914

COPY_EXISTING ~00HFSGCT.itm~ ~override~
	SAY NAME2 @11915
	SAY IDENTIFIED_DESC @11916

COPY_EXISTING ~00SLNGSS.itm~ ~override~
	SAY NAME2 @11917
	SAY IDENTIFIED_DESC @11918

COPY_EXISTING ~00HFSGSS.itm~ ~override~
	SAY NAME2 @11919
	SAY IDENTIFIED_DESC @11920


COPY_EXISTING ~11HFSGLH.itm~ ~override~
	SAY IDENTIFIED_DESC @11924


COPY_EXISTING ~00AROW05.itm~ ~override~
	SAY IDENTIFIED_DESC @11934

COPY_EXISTING ~00AROW06.itm~ ~override~
	SAY NAME2 @11935
	SAY IDENTIFIED_DESC @11936

COPY_EXISTING ~00AROW07.itm~ ~override~
	SAY IDENTIFIED_DESC @11938

COPY_EXISTING ~00AROW08.itm~ ~override~
	SAY IDENTIFIED_DESC @11940

COPY_EXISTING ~00AROW09.itm~ ~override~
	SAY IDENTIFIED_DESC @11942

COPY_EXISTING ~00AROW10.itm~ ~override~
	SAY NAME2 @11943
	SAY IDENTIFIED_DESC @11944

COPY_EXISTING ~00AROW14.itm~ ~override~
	SAY IDENTIFIED_DESC @11946

COPY_EXISTING ~00AROW85.itm~ ~override~
	SAY IDENTIFIED_DESC @11948

COPY_EXISTING ~00AROW86.itm~ ~override~
	SAY IDENTIFIED_DESC @11950

COPY_EXISTING ~00AROW87.itm~ ~override~
	SAY NAME2 @11951
	SAY IDENTIFIED_DESC @11952

COPY_EXISTING ~00AROW88.itm~ ~override~
	SAY IDENTIFIED_DESC @11954


COPY_EXISTING ~00AROW90.itm~ ~override~
	SAY IDENTIFIED_DESC @11958


COPY_EXISTING ~00AROW96.itm~ ~override~
	SAY IDENTIFIED_DESC @11970


COPY_EXISTING ~00AROW98.itm~ ~override~
	SAY NAME2 @11973
	SAY IDENTIFIED_DESC @11974

COPY_EXISTING ~00AROW99.itm~ ~override~
	SAY IDENTIFIED_DESC @11976


COPY_EXISTING ~00BOLT05.itm~ ~override~
	SAY IDENTIFIED_DESC @11986


COPY_EXISTING ~00BOLT08.itm~ ~override~
	SAY NAME2 @11987
	SAY IDENTIFIED_DESC @11988

COPY_EXISTING ~00BOLT93.itm~ ~override~
	SAY NAME2 @11989
	SAY IDENTIFIED_DESC @11990

COPY_EXISTING ~00BOLT94.itm~ ~override~
	SAY IDENTIFIED_DESC @11992

COPY_EXISTING ~00BOLT95.itm~ ~override~
	SAY IDENTIFIED_DESC @11994

COPY_EXISTING ~00BOLT96.itm~ ~override~
	SAY IDENTIFIED_DESC @11996


COPY_EXISTING ~00BULL04.itm~ ~override~
	SAY NAME2 @12009
	SAY IDENTIFIED_DESC @12010

COPY_EXISTING ~00BULL86.itm~ ~override~
	SAY IDENTIFIED_DESC @12012

COPY_EXISTING ~00BULL87.itm~ ~override~
	SAY NAME2 @12013
	SAY IDENTIFIED_DESC @12014

COPY_EXISTING ~00BULL88.itm~ ~override~
	SAY NAME2 @12015
	SAY IDENTIFIED_DESC @12016

COPY_EXISTING ~00BULL89.itm~ ~override~
	SAY NAME2 @12017
	SAY IDENTIFIED_DESC @12018

COPY_EXISTING ~00BULL90.itm~ ~override~
	SAY NAME2 @12019
	SAY IDENTIFIED_DESC @12020


COPY_EXISTING ~00BULL92.itm~ ~override~
	SAY NAME2 @12023
	SAY IDENTIFIED_DESC @12024


COPY_EXISTING ~00MISC31.itm~ ~override~
	SAY IDENTIFIED_DESC @12040

COPY_EXISTING ~USHFMC31.itm~ ~override~
	SAY IDENTIFIED_DESC @12042

COPY_EXISTING ~00MISC32.itm~ ~override~
	SAY IDENTIFIED_DESC @12044

COPY_EXISTING ~USHFMC32.itm~ ~override~
	SAY IDENTIFIED_DESC @12046

COPY_EXISTING ~00MISC37.itm~ ~override~
	SAY IDENTIFIED_DESC @12048

COPY_EXISTING ~USHFMC37.itm~ ~override~
	SAY NAME2 @12049
	SAY IDENTIFIED_DESC @12050

COPY_EXISTING ~00MISC38.itm~ ~override~
	SAY IDENTIFIED_DESC @12052

COPY_EXISTING ~00HFMC38.itm~ ~override~
	SAY IDENTIFIED_DESC @12054


COPY_EXISTING ~USHFGNIR.itm~ ~override~
	SAY IDENTIFIED_DESC @12058


COPY_EXISTING ~00GENMP.itm~ ~override~
	SAY IDENTIFIED_DESC @12064

COPY_EXISTING ~00HFGNMP.itm~ ~override~
	SAY IDENTIFIED_DESC @12066


COPY_EXISTING ~USHFGNOD.itm~ ~override~
	SAY IDENTIFIED_DESC @12074


COPY_EXISTING ~00POTN06.itm~ ~override~
	SAY IDENTIFIED_DESC @12078


COPY_EXISTING ~USHFPN07.itm~ ~override~
	SAY IDENTIFIED_DESC @12082

COPY_EXISTING ~00POTN33.itm~ ~override~
	SAY IDENTIFIED_DESC @12084

COPY_EXISTING ~00POTN34.itm~ ~override~
	SAY IDENTIFIED_DESC @12086

COPY_EXISTING ~00POTN36.itm~ ~override~
	SAY IDENTIFIED_DESC @12088

COPY_EXISTING ~00POTN45.itm~ ~override~
	SAY IDENTIFIED_DESC @12090

COPY_EXISTING ~00POTN50.itm~ ~override~
	SAY IDENTIFIED_DESC @12092

COPY_EXISTING ~00POTN53.itm~ ~override~
	SAY IDENTIFIED_DESC @12094

COPY_EXISTING ~00POTN55.itm~ ~override~
	SAY IDENTIFIED_DESC @12096

COPY_EXISTING ~00HFPN55.itm~ ~override~
	SAY IDENTIFIED_DESC @12098

COPY_EXISTING ~00POTN66.itm~ ~override~
	SAY IDENTIFIED_DESC @12100

COPY_EXISTING ~00POTN74.itm~ ~override~
	SAY IDENTIFIED_DESC @12102

COPY_EXISTING ~00POTN89.itm~ ~override~
	SAY IDENTIFIED_DESC @12104

COPY_EXISTING ~00POTN90.itm~ ~override~
	SAY NAME2 @12105
	SAY IDENTIFIED_DESC @12106

COPY_EXISTING ~00POTN91.itm~ ~override~
	SAY IDENTIFIED_DESC @12108

COPY_EXISTING ~00POTN92.itm~ ~override~
	SAY IDENTIFIED_DESC @12110

COPY_EXISTING ~00POTN93.itm~ ~override~
	SAY IDENTIFIED_DESC @12112

COPY_EXISTING ~00POTN94.itm~ ~override~
	SAY NAME2 @12113
	SAY IDENTIFIED_DESC @12114

COPY_EXISTING ~00POTN95.itm~ ~override~
	SAY NAME2 @12115
	SAY IDENTIFIED_DESC @12116

COPY_EXISTING ~00POTN96.itm~ ~override~
	SAY NAME2 @12117
	SAY IDENTIFIED_DESC @12118

COPY_EXISTING ~00POTN97.itm~ ~override~
	SAY IDENTIFIED_DESC @12120

COPY_EXISTING ~00POTN98.itm~ ~override~
	SAY IDENTIFIED_DESC @12122

COPY_EXISTING ~00POTN99.itm~ ~override~
	SAY IDENTIFIED_DESC @12124

COPY_EXISTING ~50POTN56.itm~ ~override~
	SAY IDENTIFIED_DESC @12126

COPY ~%mod_folder%/itm/USALBEET.itm~ ~override/00POTN03.itm~
  SAY NAME1 @4759
  SAY NAME2 @4759
  SAY DESC @4760
COPY ~%mod_folder%/itm/USALBEHO.itm~ ~override~
  SAY NAME1 @4761
  SAY NAME2 @4761
  SAY DESC @4762
COPY ~%mod_folder%/itm/USALBOGV.itm~ ~override~
  SAY NAME1 @4744
  SAY NAME2 @4744
  SAY DESC @4745
COPY ~%mod_folder%/itm/USALBRIN.itm~ ~override/00POTN02.itm~
  SAY NAME1 @4718
  SAY NAME2 @4718
  SAY DESC @4719
COPY ~%mod_folder%/itm/USALRAIN.itm~ ~override/00POTN04.itm~
  SAY NAME1 @4700
  SAY NAME2 @4700
  SAY DESC @4701
COPY ~%mod_folder%/itm/USALSOUR.itm~ ~override/00POTN05.itm~
  SAY NAME1 @4702
  SAY NAME2 @4702
  SAY DESC @4703
COPY ~%mod_folder%/itm/USALSWEE.itm~ ~override/00POTN10.itm~
  SAY NAME1 @4704
  SAY NAME2 @4704
  SAY DESC @4705
COPY ~%mod_folder%/itm/USALSNAK.itm~ ~override/00POTN11.itm~
  SAY NAME1 @4752
  SAY NAME2 @4752
  SAY DESC @4753
COPY ~%mod_folder%/itm/USALFISH.itm~ ~override/00POTN19.itm~
  SAY NAME1 @4771
  SAY NAME2 @4771
  SAY DESC @4772
COPY ~%mod_folder%/itm/USALCORA.itm~ ~override/00POTN20.itm~
  SAY NAME1 @4763
  SAY NAME2 @4763
  SAY DESC @4764
COPY ~%mod_folder%/itm/USALMUSK.itm~ ~override/00POTN21.itm~
  SAY NAME1 @4724
  SAY NAME2 @4724
  SAY DESC @4725
COPY ~%mod_folder%/itm/USALOGRE.itm~ ~override/00POTN22.itm~
  SAY NAME1 @4779
  SAY NAME2 @4779
  SAY DESC @4780
COPY ~%mod_folder%/itm/USALFIRE.itm~ ~override/00POTN23.itm~
  SAY NAME1 @4767
  SAY NAME2 @4767
  SAY DESC @4768
COPY ~%mod_folder%/itm/USALFROS.itm~ ~override/00POTN24.itm~
  SAY NAME1 @4769
  SAY NAME2 @4769
  SAY DESC @4770
COPY ~%mod_folder%/itm/USALBLOO.itm~ ~override/00POTN25.itm~
  SAY NAME1 @4738
  SAY NAME2 @4738
  SAY DESC @4739
COPY ~%mod_folder%/itm/USALTROL.itm~ ~override/00POTN26.itm~
  SAY NAME1 @4787
  SAY NAME2 @4787
  SAY DESC @4788
COPY ~%mod_folder%/itm/USALLIME.itm~ ~override/00POTN29.itm~
  SAY NAME1 @4726
  SAY NAME2 @4726
  SAY DESC @4727
COPY ~%mod_folder%/itm/USALGHOU.itm~ ~override/00POTN47.itm~
  SAY NAME1 @4775
  SAY NAME2 @4775
  SAY DESC @4776
COPY ~%mod_folder%/itm/USALBURN.itm~ ~override/00POTN52.itm~
  SAY NAME1 @4722
  SAY NAME2 @4722
  SAY DESC @4723
COPY ~%mod_folder%/itm/USALPLAS.itm~ ~override/00POTN54.itm~
  SAY NAME1 @4742
  SAY NAME2 @4742
  SAY DESC @4743
COPY ~%mod_folder%/itm/USALSMOK.itm~ ~override/00POTN67.itm~
  SAY NAME1 @4714
  SAY NAME2 @4714
  SAY DESC @4715
COPY ~%mod_folder%/itm/USALMAGN.itm~ ~override/00POTN68.itm~
  SAY NAME1 @4748
  SAY NAME2 @4748
  SAY DESC @4749
COPY ~%mod_folder%/spl/USMAGN00.spl~ ~override~
COPY ~%mod_folder%/itm/USALPRES.itm~ ~override/00POTN69.itm~
  SAY NAME1 @4720
  SAY NAME2 @4720
  SAY DESC @4721
COPY ~%mod_folder%/itm/USALTREA.itm~ ~override/00POTN70.itm~
  SAY NAME1 @4785
  SAY NAME2 @4785
  SAY DESC @4786
COPY ~%mod_folder%/itm/USALFEYR.itm~ ~override/00POTN71.itm~
  SAY NAME1 @4765
  SAY NAME2 @4765
  SAY DESC @4766
COPY ~%mod_folder%/itm/USALRADI.itm~ ~override/00POTN72.itm~
  SAY NAME1 @4708
  SAY NAME2 @4708
  SAY DESC @4709
COPY ~%mod_folder%/itm/USALBLAC.itm~ ~override/00POTN73.itm~
  SAY NAME1 @4710
  SAY NAME2 @4710
  SAY DESC @4711
COPY ~%mod_folder%/itm/USALFIZZ.itm~ ~override/00POTN75.itm~
  SAY NAME1 @4773
  SAY NAME2 @4773
  SAY DESC @4774
COPY ~%mod_folder%/itm/USALBUR2.itm~ ~override/00POTN76.itm~
  SAY NAME1 @4750
  SAY NAME2 @4750
  SAY DESC @4751
COPY ~%mod_folder%/itm/USALVIAL.itm~ ~override/00POTN77.itm~
  SAY NAME1 @4728
  SAY NAME2 @4728
  SAY DESC @4729
COPY ~%mod_folder%/itm/USALVAMP.itm~ ~override/00POTN78.itm~
  SAY NAME1 @4754
  SAY NAME2 @4754
  SAY DESC @4755
COPY ~%mod_folder%/itm/USALGOLD.itm~ ~override/00POTN79.itm~
  SAY NAME1 @4777
  SAY NAME2 @4777
  SAY DESC @4778
COPY ~%mod_folder%/itm/USALECTO.itm~ ~override/00POTN80.itm~
  SAY NAME1 @4730
  SAY NAME2 @4730
  SAY DESC @4731
COPY ~%mod_folder%/itm/USALOILS.itm~ ~override/00POTN81.itm~
  SAY NAME1 @4781
  SAY NAME2 @4781
  SAY DESC @4782
COPY ~%mod_folder%/itm/USALBONE.itm~ ~override/00POTN82.itm~
  SAY NAME1 @4712
  SAY NAME2 @4712
  SAY DESC @4713
COPY ~%mod_folder%/itm/USALBITT.itm~ ~override/00POTN83.itm~
  SAY NAME1 @4716
  SAY NAME2 @4716
  SAY DESC @4717
COPY ~%mod_folder%/itm/USALCLAR.itm~ ~override/00POTN84.itm~
  SAY NAME1 @4783
  SAY NAME2 @4783
  SAY DESC @4784
COPY ~%mod_folder%/itm/USALELEC.itm~ ~override/00POTN85.itm~
  SAY NAME1 @4706
  SAY NAME2 @4706
  SAY DESC @4707
COPY ~%mod_folder%/itm/USALFAIR.itm~ ~override/00POTN86.itm~
  SAY NAME1 @4746
  SAY NAME2 @4746
  SAY DESC @4747
COPY ~%mod_folder%/itm/USALMURK.itm~ ~override/00POTN87.itm~
  SAY NAME1 @4736
  SAY NAME2 @4736
  SAY DESC @4737
COPY ~%mod_folder%/itm/USALZOMB.itm~ ~override/00POTN88.itm~
  SAY NAME1 @4789
  SAY NAME2 @4789
  SAY DESC @4790
COPY ~%mod_folder%/itm/USALVIA2.itm~ ~override/61POTNUB.itm~
  SAY NAME1 @4791
  SAY NAME2 @4791
  SAY DESC @4792


COPY_EXISTING ~00BARD02.itm~ ~override~
	SAY IDENTIFIED_DESC @12132

COPY_EXISTING ~00HFBD02.itm~ ~override~
	SAY IDENTIFIED_DESC @12134

COPY_EXISTING ~00BARD03.itm~ ~override~
	SAY IDENTIFIED_DESC @12136

COPY_EXISTING ~00HFBD03.itm~ ~override~
	SAY IDENTIFIED_DESC @12138


COPY_EXISTING ~00HFBD04.itm~ ~override~
	SAY IDENTIFIED_DESC @12142

COPY_EXISTING ~00BARD05.itm~ ~override~
	SAY IDENTIFIED_DESC @12144

COPY_EXISTING ~00HFBD05.itm~ ~override~
	SAY IDENTIFIED_DESC @12146

COPY_EXISTING ~00BARD06.itm~ ~override~
	SAY IDENTIFIED_DESC @12148

COPY_EXISTING ~00HFBD06.itm~ ~override~
	SAY IDENTIFIED_DESC @12150

COPY_EXISTING ~00BARD07.itm~ ~override~
	SAY IDENTIFIED_DESC @12152

COPY_EXISTING ~00HFBD07.itm~ ~override~
	SAY IDENTIFIED_DESC @12154

COPY_EXISTING ~00BARD08.itm~ ~override~
	SAY IDENTIFIED_DESC @12156

COPY_EXISTING ~00HFBD08.itm~ ~override~
	SAY IDENTIFIED_DESC @12158

COPY_EXISTING ~00BARDRS.itm~ ~override~
	SAY IDENTIFIED_DESC @12160

COPY_EXISTING ~00HFBDRS.itm~ ~override~
	SAY NAME2 @12161
	SAY IDENTIFIED_DESC @12162

COPY_EXISTING ~11BARDWD.itm~ ~override~
	SAY IDENTIFIED_DESC @12164

COPY_EXISTING ~11HFBDWD.itm~ ~override~
	SAY IDENTIFIED_DESC @12166


COPY_EXISTING ~00SCRL01.itm~ ~override~
	SAY IDENTIFIED_DESC @12168

COPY_EXISTING ~00SCRL02.itm~ ~override~
	SAY IDENTIFIED_DESC @12170

COPY_EXISTING ~00SCRL03.itm~ ~override~
	SAY IDENTIFIED_DESC @12172

COPY_EXISTING ~00SCRL04.itm~ ~override~
	SAY IDENTIFIED_DESC @12174


COPY_EXISTING ~00SCRL06.itm~ ~override~
	SAY IDENTIFIED_DESC @12178


COPY_EXISTING ~11BOOKDE.itm~ ~override~
	SAY IDENTIFIED_DESC @12198

COPY_EXISTING ~11HFBKDE.itm~ ~override~
	SAY IDENTIFIED_DESC @12200

COPY_EXISTING ~11HFBKHW.itm~ ~override~
	SAY IDENTIFIED_DESC @12202

COPY_EXISTING ~11HFBKLD.itm~ ~override~
	SAY IDENTIFIED_DESC @12204


COPY_EXISTING ~11HFBKLE.itm~ ~override~
	SAY IDENTIFIED_DESC @12208

COPY_EXISTING ~52BOOKAD.itm~ ~override~
	SAY IDENTIFIED_DESC @12210

COPY_EXISTING ~52HFBKAD.itm~ ~override~
	SAY IDENTIFIED_DESC @12212


COPY_EXISTING ~52HFBKDV.itm~ ~override~
	SAY IDENTIFIED_DESC @12216


COPY_EXISTING ~52BOOKOG.itm~ ~override~
	SAY IDENTIFIED_DESC @12222

COPY_EXISTING ~52HFBKOG.itm~ ~override~
	SAY IDENTIFIED_DESC @12224


COPY_EXISTING ~52HFBKSU.itm~ ~override~
	SAY IDENTIFIED_DESC @12228

COPY_EXISTING ~52BOOKSV.itm~ ~override~
	SAY NAME2 @12229
	SAY IDENTIFIED_DESC @12230

COPY_EXISTING ~52HFBKSV.itm~ ~override~
	SAY NAME2 @12231
	SAY IDENTIFIED_DESC @12232


COPY_EXISTING ~00WAND01.itm~ ~override~
	SAY IDENTIFIED_DESC @12234

COPY_EXISTING ~00WAND02.itm~ ~override~
	SAY IDENTIFIED_DESC @12236

COPY_EXISTING ~00WAND03.itm~ ~override~
	SAY IDENTIFIED_DESC @12238

COPY_EXISTING ~00WAND04.itm~ ~override~
	SAY IDENTIFIED_DESC @12240

COPY_EXISTING ~00WAND05.itm~ ~override~
	SAY IDENTIFIED_DESC @12242


COPY_EXISTING ~00WAND08.itm~ ~override~
	SAY IDENTIFIED_DESC @12248


COPY_EXISTING ~00WAND14.itm~ ~override~
	SAY IDENTIFIED_DESC @12252

COPY_EXISTING ~00WAND15.itm~ ~override~
	SAY IDENTIFIED_DESC @12254

COPY_EXISTING ~00WAND16.itm~ ~override~
	SAY NAME2 @12255
	SAY IDENTIFIED_DESC @12256


COPY_EXISTING ~00WAND20.itm~ ~override~
	SAY NAME2 @12261
	SAY IDENTIFIED_DESC @12262

COPY_EXISTING ~00WAND21.itm~ ~override~
	SAY IDENTIFIED_DESC @12264

COPY_EXISTING ~00WAND22.itm~ ~override~
	SAY NAME2 @12265
	SAY IDENTIFIED_DESC @12266

COPY_EXISTING ~00WAND23.itm~ ~override~
	SAY IDENTIFIED_DESC @12268

COPY_EXISTING ~00WAND24.itm~ ~override~
	SAY NAME2 @12269
	SAY IDENTIFIED_DESC @12270

COPY_EXISTING ~00WAND25.itm~ ~override~
	SAY IDENTIFIED_DESC @12272

COPY_EXISTING ~00WAND26.itm~ ~override~
	SAY NAME2 @12273
	SAY IDENTIFIED_DESC @12274

COPY_EXISTING ~00WAND27.itm~ ~override~
	SAY IDENTIFIED_DESC @12276

COPY_EXISTING ~00WAND28.itm~ ~override~
	SAY IDENTIFIED_DESC @12278

COPY_EXISTING ~00WAND29.itm~ ~override~
	SAY IDENTIFIED_DESC @12280


COPY_EXISTING ~00WAND33.itm~ ~override~
	SAY IDENTIFIED_DESC @12288

COPY_EXISTING ~00WAND34.itm~ ~override~
	SAY IDENTIFIED_DESC @12290

COPY_EXISTING ~00WAND35.itm~ ~override~
	SAY NAME2 @12291
	SAY IDENTIFIED_DESC @12292

COPY_EXISTING ~00WAND36.itm~ ~override~
	SAY IDENTIFIED_DESC @12294

COPY_EXISTING ~00WAND37.itm~ ~override~
	SAY IDENTIFIED_DESC @12296


COPY_EXISTING ~00WAND39.itm~ ~override~
	SAY IDENTIFIED_DESC @12300

COPY_EXISTING ~00WAND40.itm~ ~override~
	SAY IDENTIFIED_DESC @12302


COPY_EXISTING ~00WAND42.itm~ ~override~
	SAY IDENTIFIED_DESC @12306

COPY_EXISTING ~00WAND43.itm~ ~override~
	SAY NAME2 @12307
	SAY IDENTIFIED_DESC @12308


COPY_EXISTING ~00WAND45.itm~ ~override~
	SAY NAME2 @12311
	SAY IDENTIFIED_DESC @12312


//Pre-existing items for which room was not made in the TRA file go below

COPY_EXISTING ~00HELM07.itm~ ~override~
	SAY IDENTIFIED_DESC @12314

COPY_EXISTING ~61GENWP.itm~ ~override~
	SAY UNIDENTIFIED_DESC @12316

COPY_EXISTING ~61pbrewt.bcs~ ~override~
	DECOMPILE_AND_PATCH BEGIN
		REPLACE_TEXTUALLY CASE_INSENSITIVE ~GiveItemCreate(\"61GenWP\",\"PoisonTable\",1,0,0)~ ~GiveItemCreate("61GenWP","PoisonTable",3,0,0)~
		REPLACE_TEXTUALLY CASE_INSENSITIVE ~Global(\"61ExitTo6104Open\",\"GLOBAL\",1)~ ~False()~
	END


//New items go below. The initial items have been sorted by item type, but items made later should just go at the end, regardless of their type.

COPY_EXISTING ~USAMUL47.itm~ ~override~
	SAY NAME2 @12413
	SAY IDENTIFIED_DESC @12414

COPY_EXISTING ~USAMUL50.itm~ ~override~
	SAY NAME2 @12415
	SAY IDENTIFIED_DESC @12416

COPY_EXISTING ~USAMUL51.itm~ ~override~
	SAY NAME2 @12417
	SAY IDENTIFIED_DESC @12418

COPY_EXISTING ~USAMUL56.itm~ ~override~
	SAY NAME2 @12419
	SAY IDENTIFIED_DESC @12420

COPY_EXISTING ~USAMUL58.itm~ ~override~
	SAY NAME2 @12421
	SAY IDENTIFIED_DESC @12422

COPY_EXISTING ~USAMUL59.itm~ ~override~
	SAY NAME2 @12423
	SAY IDENTIFIED_DESC @12424

COPY_EXISTING ~USAX1H48.itm~ ~override~
	SAY NAME2 @12425
	SAY IDENTIFIED_DESC @12426

COPY_EXISTING ~USBOLT45.itm~ ~override~
	SAY NAME2 @12427
	SAY IDENTIFIED_DESC @12428

COPY_EXISTING ~USBOOT59.itm~ ~override~
	SAY NAME2 @12429
	SAY IDENTIFIED_DESC @12430

COPY_EXISTING ~USBRAC47.itm~ ~override~
	SAY NAME2 @12431
	SAY IDENTIFIED_DESC @12432

COPY_EXISTING ~USBRAC50.itm~ ~override~
	SAY NAME2 @12433
	SAY IDENTIFIED_DESC @12434

COPY_EXISTING ~USBRAC55.itm~ ~override~
	SAY NAME2 @12435
	SAY IDENTIFIED_DESC @12436

COPY_EXISTING ~USBRAC57.itm~ ~override~
	SAY NAME2 @12437
	SAY IDENTIFIED_DESC @12438

COPY_EXISTING ~USBRAC59.itm~ ~override~
	SAY NAME2 @12439
	SAY IDENTIFIED_DESC @12440

COPY_EXISTING ~USBWHX57.itm~ ~override~
	SAY NAME2 @12441
	SAY IDENTIFIED_DESC @12442

COPY_EXISTING ~USCHAN40.itm~ ~override~
	SAY NAME2 @12443
	SAY IDENTIFIED_DESC @12444

COPY_EXISTING ~USCHAN41.itm~ ~override~
	SAY NAME2 @12445
	SAY IDENTIFIED_DESC @12446

COPY_EXISTING ~USCHAN48.itm~ ~override~
	SAY NAME2 @12447
	SAY IDENTIFIED_DESC @12448

COPY_EXISTING ~USCHAN49.itm~ ~override~
	SAY NAME2 @12449
	SAY IDENTIFIED_DESC @12450

COPY_EXISTING ~USCHAN52.itm~ ~override~
	SAY NAME2 @12451
	SAY IDENTIFIED_DESC @12452

COPY_EXISTING ~USCHAN54.itm~ ~override~
	SAY NAME2 @12453
	SAY IDENTIFIED_DESC @12454

COPY_EXISTING ~USCHAN59.itm~ ~override~
	SAY NAME2 @12455
	SAY IDENTIFIED_DESC @12456

COPY_EXISTING ~USCLCK40.itm~ ~override~
	SAY NAME2 @12457
	SAY IDENTIFIED_DESC @12458

COPY_EXISTING ~USCLCK50.itm~ ~override~
	SAY NAME2 @12459
	SAY IDENTIFIED_DESC @12460

COPY_EXISTING ~USCLCK51.itm~ ~override~
	SAY NAME2 @12461
	SAY IDENTIFIED_DESC @12462

COPY_EXISTING ~USCLCK55.itm~ ~override~
	SAY NAME2 @12463
	SAY IDENTIFIED_DESC @12464

COPY_EXISTING ~USCLCKMH.itm~ ~override~
	SAY NAME2 @12465
	SAY IDENTIFIED_DESC @12466

COPY_EXISTING ~USDAGG53.itm~ ~override~
	SAY NAME2 @12467
	SAY IDENTIFIED_DESC @12468

COPY_EXISTING ~USDAGG59.itm~ ~override~
	SAY NAME2 @12469
	SAY IDENTIFIED_DESC @12470

COPY_EXISTING ~USDART59.itm~ ~override~
	SAY NAME2 @12471
	SAY IDENTIFIED_DESC @12472

COPY_EXISTING ~USHAMT48.itm~ ~override~
	SAY NAME2 @12473
	SAY IDENTIFIED_DESC @12474

COPY_EXISTING ~USHELM50.itm~ ~override~
	SAY NAME2 @12475
	SAY IDENTIFIED_DESC @12476

COPY_EXISTING ~USHELM59.itm~ ~override~
	SAY NAME2 @12477
	SAY IDENTIFIED_DESC @12478

COPY_EXISTING ~USHIDEGU.itm~ ~override~
	SAY NAME2 @12479
	SAY IDENTIFIED_DESC @12480

COPY_EXISTING ~USHFHDGU.itm~ ~override~
	SAY NAME2 @12481
	SAY IDENTIFIED_DESC @12482

COPY_EXISTING ~USHIDE49.itm~ ~override~
	SAY NAME2 @12483
	SAY IDENTIFIED_DESC @12484

COPY_EXISTING ~USHIDE59.itm~ ~override~
	SAY NAME2 @12485
	SAY IDENTIFIED_DESC @12486

COPY_EXISTING ~USLEAT48.itm~ ~override~
	SAY NAME2 @12487
	SAY IDENTIFIED_DESC @12488

COPY_EXISTING ~USLEAT51.itm~ ~override~
	SAY NAME2 @12489
	SAY IDENTIFIED_DESC @12490

COPY_EXISTING ~USLEAT57.itm~ ~override~
	SAY NAME2 @12491
	SAY IDENTIFIED_DESC @12492

COPY_EXISTING ~USLEAT58.itm~ ~override~
	SAY NAME2 @12493
	SAY IDENTIFIED_DESC @12494

COPY_EXISTING ~USLEAT59.itm~ ~override~
	SAY NAME2 @12495
	SAY IDENTIFIED_DESC @12496

COPY_EXISTING ~USPLAT35.itm~ ~override~
	SAY NAME2 @12497
	SAY IDENTIFIED_DESC @12498

COPY_EXISTING ~USPLAT45.itm~ ~override~
	SAY NAME2 @12499
	SAY IDENTIFIED_DESC @12500

COPY_EXISTING ~USPLAT48.itm~ ~override~
	SAY NAME2 @12501
	SAY IDENTIFIED_DESC @12502

COPY_EXISTING ~USPLAT51.itm~ ~override~
	SAY NAME2 @12503
	SAY IDENTIFIED_DESC @12504

COPY_EXISTING ~USPLAT58.itm~ ~override~
	SAY NAME2 @12505
	SAY IDENTIFIED_DESC @12506

COPY_EXISTING ~USPLAT59.itm~ ~override~
	SAY NAME2 @12507
	SAY IDENTIFIED_DESC @12508

COPY_EXISTING ~USRING50.itm~ ~override~
	SAY NAME2 @12509
	SAY IDENTIFIED_DESC @12510

COPY_EXISTING ~USRING51.itm~ ~override~
	SAY NAME2 @12511
	SAY IDENTIFIED_DESC @12512

COPY_EXISTING ~USRING52.itm~ ~override~
	SAY NAME2 @12513
	SAY IDENTIFIED_DESC @12514

COPY_EXISTING ~USRING53.itm~ ~override~
	SAY NAME2 @12515
	SAY IDENTIFIED_DESC @12516

COPY_EXISTING ~USRING55.itm~ ~override~
	SAY NAME2 @12517
	SAY IDENTIFIED_DESC @12518

COPY_EXISTING ~USRING56.itm~ ~override~
	SAY NAME2 @12519
	SAY IDENTIFIED_DESC @12520

COPY_EXISTING ~USRING58.itm~ ~override~
	SAY NAME2 @12521
	SAY IDENTIFIED_DESC @12522

COPY_EXISTING ~USROBE56.itm~ ~override~
	SAY NAME2 @12523
	SAY IDENTIFIED_DESC @12524

COPY_EXISTING ~USROBE59.itm~ ~override~
	SAY NAME2 @12525
	SAY IDENTIFIED_DESC @12526

COPY_EXISTING ~USSHLD48.itm~ ~override~
	SAY NAME2 @12527
	SAY IDENTIFIED_DESC @12528

COPY_EXISTING ~USSHLD49.itm~ ~override~
	SAY NAME2 @12529
	SAY IDENTIFIED_DESC @12530

COPY_EXISTING ~USSHLD50.itm~ ~override~
	SAY NAME2 @12531
	SAY IDENTIFIED_DESC @12532

COPY_EXISTING ~USSHLD51.itm~ ~override~
	SAY NAME2 @12533
	SAY IDENTIFIED_DESC @12534

COPY_EXISTING ~USSHLD55.itm~ ~override~
	SAY NAME2 @12535
	SAY IDENTIFIED_DESC @12536

COPY_EXISTING ~USSHLD56.itm~ ~override~
	SAY NAME2 @12537
	SAY IDENTIFIED_DESC @12538

COPY_EXISTING ~USSHLD57.itm~ ~override~
	SAY NAME2 @12539
	SAY IDENTIFIED_DESC @12540

COPY_EXISTING ~USSHLD58.itm~ ~override~
	SAY NAME2 @12541
	SAY IDENTIFIED_DESC @12542

COPY_EXISTING ~USSHLD59.itm~ ~override~
	SAY NAME2 @12543
	SAY IDENTIFIED_DESC @12544

COPY_EXISTING ~USSLNG59.itm~ ~override~
	SAY NAME2 @12545
	SAY IDENTIFIED_DESC @12546

COPY_EXISTING ~USSWDK59.itm~ ~override~
	SAY NAME1 @12547
	SAY UNIDENTIFIED_DESC @12548
	SAY NAME2 @12549
	SAY IDENTIFIED_DESC @12550

COPY_EXISTING ~USSWDT59.itm~ ~override~
	SAY NAME2 @12551
	SAY IDENTIFIED_DESC @12552

COPY_EXISTING ~USAROW47.itm~ ~override~
	SAY NAME2 @12553
	SAY IDENTIFIED_DESC @12554

COPY_EXISTING ~USAROW48.itm~ ~override~
	SAY NAME2 @12555
	SAY IDENTIFIED_DESC @12556

COPY_EXISTING ~USAROW49.itm~ ~override~
	SAY NAME2 @12557
	SAY IDENTIFIED_DESC @12558

COPY_EXISTING ~USAROW52.itm~ ~override~
	SAY NAME2 @12559
	SAY IDENTIFIED_DESC @12560

COPY_EXISTING ~USAROW59.itm~ ~override~
	SAY NAME2 @12561
	SAY IDENTIFIED_DESC @12562

COPY_EXISTING ~USBOLT47.itm~ ~override~
	SAY NAME2 @12563
	SAY IDENTIFIED_DESC @12564

COPY_EXISTING ~USBOLT48.itm~ ~override~
	SAY NAME2 @12565
	SAY IDENTIFIED_DESC @12566

COPY_EXISTING ~USBOLT52.itm~ ~override~
	SAY NAME2 @12567
	SAY IDENTIFIED_DESC @12568

COPY_EXISTING ~USBOLT53.itm~ ~override~
	SAY NAME2 @12569
	SAY IDENTIFIED_DESC @12570

COPY_EXISTING ~USBULL48.itm~ ~override~
	SAY NAME2 @12571
	SAY IDENTIFIED_DESC @12572

COPY_EXISTING ~USBULL53.itm~ ~override~
	SAY NAME2 @12573
	SAY IDENTIFIED_DESC @12574

COPY_EXISTING ~USFLAL59.itm~ ~override~
	SAY NAME2 @12575
	SAY IDENTIFIED_DESC @12576


//General patch changes

COPY_EXISTING_REGEXP ~.*\.itm~ ~override~
//If the item is a bullet, it should apply Strength bonus
	READ_SHORT 0x1c us_item_category
	PATCH_IF (us_item_category=14) BEGIN
		LPF ALTER_ITEM_HEADER INT_VAR header_type=2 flag_strength=1 END
	END
	BUT_ONLY_IF_IT_CHANGES


//Random loot table changes

COPY_EXISTING ~%mod_folder%/tables/tables_item_revisions~ ~override~

APPEND ~RT_NORM.2da~
~
USRTHF01	00SPER08
USRTHF02	00SWDT93
USRTHF03	50HIDE06
USRTHF04	50BOOT14
USRTHF05	50CLCK17
USRTHF06	53CLCKHD
USRTHF07	53AMULHD
USRTHF08	53AMULBS
USRTHF09	11BELTMK
USRTHF10	00FLAL03
USRTHF11	00GENIR
USRTHF12	00GENOD
USRTHF13	40GENPWC
USRTHF14	00HIDE04
USRTHF15	USHIDEGU
USRTHF16	41AX1HAI
USRTHF17	00MISC31
USRTHF18	00MISC32
USRTHF19	00MISC37
USRTHF20	00RING19
USRTHF21	00RING20
USRTHF22	00RING91
USRTHF23	00CLCK01
USRTHF24	00CLCK02
USRTHF25	USCLCK40
USRTHF26	00BRAC02
USRTHF27	00BRAC03
USRTHF28	00BRAC04
USRTHF29	USBRAC47
USRTHF30	00POTN07
USRTHF31	00BELT05
USRTHF32	12SHLDCT
USRTHF33	12SHLDKD
USRTHF34	12SHLDSG
USRTHF35	00CLCKWC
~	        
APPEND ~RT_FURY.2da~
~
USRTHF01	USHFSR08
USRTHF02	USHFST93
USRTHF03	USHFHDWH
USRTHF04	USHFBTWH
USRTHF05	USHFCKWH
USRTHF06	USHFCKHD
USRTHF07	USHFAMHD
USRTHF08	USHFAMBS
USRTHF09	USHFBTMK
USRTHF10	USHFFL03
USRTHF11	USHFGNIR
USRTHF12	USHFGNOD
USRTHF13	USHFGNWC
USRTHF14	USHFHD04
USRTHF15	USHFHDGU
USRTHF16	USHFAXAI
USRTHF17	USHFMC31
USRTHF18	USHFMC32
USRTHF19	USHFMC37
USRTHF20	00RING91
USRTHF21	USRING50
USRTHF22	USRING55
USRTHF23	USCLCK40
USRTHF24	USCLCK50
USRTHF25	USCLCK55
USRTHF26	USBRAC47
USRTHF27	USBRAC50
USRTHF28	USBRAC55
USRTHF29	USBRAC55
USRTHF30	USHFPN07
USRTHF31	USHFBT05
USRTHF32	12HFSDCT
USRTHF33	12HFSDKD
USRTHF34	12HFSDSG
USRTHF35	00HFCKWC
~

//New items and item relocations

ACTION_IF !(FILE_EXISTS_IN_GAME 00hfsdtcl.itm) BEGIN //If Black Isle's official patch 201 is not installed
	COPY_EXISTING ~50NYM2.sto~ ~override~ //Nym store
		ADD_STORE_ITEM ~PTCHRT01~ #1 #1 #1 ~IDENTIFIED~ #1 //Myrkul armor
		ADD_STORE_ITEM ~PTCHRT06~ #1 #1 #1 ~IDENTIFIED~ #1 //Mercenaries' Lot armor

	COPY_EXISTING ~00BASHS3.sto~ ~override~ //Avarine Decanter genie store
		ADD_STORE_ITEM ~PTCHRT02~ #1 #1 #1 ~IDENTIFIED~ #1 //Air Genasi armor

	COPY_EXISTING ~53HEGGR.sto~ ~override~ //Underdark weapon/armor store
		ADD_STORE_ITEM ~PTCHRT04~ AFTER ~00CHAN02~ #1 #1 #1 ~IDENTIFIED~ #1 //Fiend plate armor
		ADD_STORE_ITEM ~PTCHRT05~ AFTER ~00CHAN02~ #1 #1 #1 ~IDENTIFIED~ #1 //Diamond plate armor
	COPY_EXISTING ~60SHEEMI.sto~ ~override~ //Conlan store
		ADD_STORE_ITEM ~PTCHRT07~ #1 #1 #1 ~IDENTIFIED~ #1 //Aasimar's Aura armor
		ADD_STORE_ITEM ~PTCHRT03~ #1 #1 #1 ~IDENTIFIED~ #1 //Tuqak Mauler's armor

END

ACTION_IF !(MOD_IS_INSTALLED ~Setup-IWD2-Ease.tp2~ ~14~) BEGIN //If Stronger Bastard Swords from IWD2-Ease is not installed
	COPY_EXISTING ~11deird.sto~ ~override~ //Gallaway Trading Post
		ADD_STORE_ITEM ~00SWDB99~ AFTER ~00SWDB02~ #1 #1 #1 ~IDENTIFIED~ #1 //Fang
END

ACTION_IF !(MOD_IS_INSTALLED ~Setup-IWD2-Ease.tp2~ ~18~) BEGIN //If Include Forgotten Armor and Shields is not installed

	COPY_EXISTING ~30GOBKRU.dlg~ ~override~ //Kruntur dialogue
		DECOMPILE_DLG_TO_D
		REPLACE_TEXTUALLY CASE_INSENSITIVE ~RARM_02~ ~USRTHF34~ //Sad Giant's Cap
		COMPILE_D_TO_DLG
		LPF CONVERT_DLG_TO_IWD2_FORMAT END


	COPY_EXISTING ~11DEIRD.sto~ ~override~ //Gallaway Trading Post
		ADD_STORE_ITEM ~60RTHF06~ AFTER ~00PLAT01~ #1 #1 #1 ~IDENTIFIED~ #1 //Owl's Feather
		ADD_STORE_ITEM ~USRTHF32~ AFTER ~00SHLD03~ #1 #1 #1 ~IDENTIFIED~ #1 //Cliffs of Targos

	COPY_EXISTING ~20arte.sto~ ~override~ //Shaengarne villager store
		ADD_STORE_ITEM ~USRTHF33~ AFTER ~00SHLD01~ #1 #1 #1 ~IDENTIFIED~ #1 //Knucklehead Shield

	COPY_EXISTING ~50NYM2.sto~ ~override~ //Nym store
		ADD_STORE_ITEM ~00CHAN07~ #1 #1 #1 ~IDENTIFIED~ #1 //Elven Chainmail +1

	COPY_EXISTING ~53WODE.sto~ ~override~ //Underdark ranged ammunition store
		ADD_STORE_ITEM ~00LEAT08~ #1 #1 #1 ~IDENTIFIED~ #1 //Mourner's Armor

	COPY_EXISTING ~60SHEEMI.sto~ ~override~ //Conlan store
		ADD_STORE_ITEM ~60RTHF02~ #1 #1 #1 ~IDENTIFIED~ #1 //Interloper armor

	COPY_EXISTING ~61RAKSHA.sto~ ~override~  //Rakshasa Nathaniel store
		ADD_STORE_ITEM ~60RTHF04~ #1 #1 #1 ~IDENTIFIED~ #1 //Glacial Resilience armor


	COPY_EXISTING ~41Ingrat.cre~ ~override~ //Doppelganger Neverwinter Captain
		LPF IWD2_ADD_CRE_ITEM INT_VAR cq1=1 STR_VAR item=~60RTHF05~ slot=~armor~ END
END 

COPY_EXISTING ~10guthe.sto~ ~override~ //Salty Dog Barbarian store
	ADD_STORE_ITEM ~00BOOT15~ #1 #1 #1 ~IDENTIFIED~ #1 //Winter Wolf Boots
	ADD_STORE_ITEM ~00CLCK18~ #1 #1 #1 ~IDENTIFIED~ #1 //Winter Wolf Cloak
	ADD_STORE_ITEM ~00BRAC18~ #1 #1 #1 ~IDENTIFIED~ #1 //Winter Wolf Gloves
	ADD_STORE_ITEM ~00AMUL32~ #1 #1 #1 ~IDENTIFIED~ #1 //Winter Wolf Scarf
	ADD_STORE_ITEM ~00HELM19~ #1 #1 #1 ~IDENTIFIED~ #1 //Winter Wolf Hat
	ADD_STORE_ITEM ~00BOOT14~ #1 #1 #1 ~IDENTIFIED~ #6 //Yeti Boots
	ADD_STORE_ITEM ~00CLCK17~ #1 #1 #1 ~IDENTIFIED~ #6 //Yeti Cloak
	ADD_STORE_ITEM ~00BRAC17~ #1 #1 #1 ~IDENTIFIED~ #6 //Yeti Gloves
	ADD_STORE_ITEM ~00AMUL31~ #1 #1 #1 ~IDENTIFIED~ #6 //Yeti Scarf
	ADD_STORE_ITEM ~00HELM18~ #1 #1 #1 ~IDENTIFIED~ #6 //Yeti Hat
	ADD_STORE_ITEM ~00BOWP01~ AFTER ~00BOWS01~ #1 #1 #1 ~IDENTIFIED~ #1 //Composite Shortbow
	ADD_STORE_ITEM ~10RTHF02~ AFTER ~00LEAT04~ #1 #1 #1 ~IDENTIFIED~ #1 //Uthgar's Blessing

COPY_EXISTING ~11deird.sto~ ~override~ //Gallaway Trading Post
	ADD_STORE_ITEM ~00SHLD16~ AFTER ~00SHLD15~ #1 #1 #1 ~IDENTIFIED~ #1 //Tower Shield +1
	ADD_STORE_ITEM ~00BOWP01~ AFTER ~00BOWS01~ #1 #1 #1 ~IDENTIFIED~ #2 //Composite Shortbow
	ADD_STORE_ITEM ~00BOWC01~ AFTER ~00BOWL01~ #1 #1 #1 ~IDENTIFIED~ #2 //Composite Longbow
	ADD_STORE_ITEM ~00BOWC02~ AFTER ~00BOWC01~ #1 #1 #1 ~IDENTIFIED~ #1 //Masterwork Composite Longbow
	ADD_STORE_ITEM ~00BWLX02~ AFTER ~00BWLX01~ #1 #1 #1 ~IDENTIFIED~ #1 //Masterwork Light Crossbow
	ADD_STORE_ITEM ~00BWLX99~ AFTER ~00BWLX02~ #1 #1 #1 ~IDENTIFIED~ #1 //Light Crossbow of Accuracy
	ADD_STORE_ITEM ~00BWHX02~ AFTER ~00BWHX01~ #1 #1 #1 ~IDENTIFIED~ #1 //Masterwork Heavy Crossbow
	ADD_STORE_ITEM ~00RTHF55~ AFTER ~00BWHX02~ #1 #1 #1 ~IDENTIFIED~ #1 //Mailripper
	ADD_STORE_ITEM ~00RTHF15~ AFTER ~00DART02~ #20 #0 #0 ~IDENTIFIED~ #2 //Adron's Theorem darts

COPY_EXISTING ~11elytha.sto~ ~override~ //Elytharra store
	ADD_STORE_ITEM ~00RING87~ AFTER ~00RING75~ #1 #1 #1 ~IDENTIFIED~ #1 //Lesser Chameleon Ring
	ADD_STORE_ITEM ~00RING21~ AFTER ~00RING87~ #1 #1 #1 ~IDENTIFIED~ #1 //Wizard's Ring
	ADD_STORE_ITEM ~00RING86~ AFTER ~00RING21~ #1 #1 #1 ~IDENTIFIED~ #1 //Ring of Beauty
	ADD_STORE_ITEM ~00ROBE01~ BEFORE ~00ROBE03~ #1 #1 #1 ~IDENTIFIED~ #1 //Robe of Cold Resistance
	ADD_STORE_ITEM ~00ROBE04~ AFTER ~00ROBE03~ #1 #1 #1 ~IDENTIFIED~ #1 //Adventurer's Robe
	ADD_STORE_ITEM ~00ROBE02~ AFTER ~00ROBE04~ #1 #1 #1 ~IDENTIFIED~ #1 //Knave's Robe
	ADD_STORE_ITEM ~00WAND06~ AFTER ~00WAND14~ #50 #1 #1 ~IDENTIFIED~ #1 //Wand of Sleep
	ADD_STORE_ITEM ~00WAND20~ AFTER ~00WAND06~ #50 #1 #1 ~IDENTIFIED~ #1 //Ice Dagger Wand
	ADD_STORE_ITEM ~00WAND21~ AFTER ~00WAND20~ #50 #1 #1 ~IDENTIFIED~ #1 //Wand of Burning Hands
	ADD_STORE_ITEM ~00WAND22~ AFTER ~00WAND21~ #50 #1 #1 ~IDENTIFIED~ #1 //Wand of Magic Armor
	ADD_STORE_ITEM ~00WAND23~ AFTER ~00WAND22~ #50 #1 #1 ~IDENTIFIED~ #1 //Chromatic Orb Wand
	ADD_STORE_ITEM ~00WAND24~ AFTER ~00WAND23~ #50 #1 #1 ~IDENTIFIED~ #1 //Wand of Dazzling Colors
	ADD_STORE_ITEM ~00WAND29~ AFTER ~00WAND24~ #50 #1 #1 ~IDENTIFIED~ #1 //Wand of Enfeeblement
	ADD_STORE_ITEM ~00WAND31~ AFTER ~00WAND29~ #50 #1 #1 ~IDENTIFIED~ #1 //Wand of Protection from Evil
	ADD_STORE_ITEM ~00RTHF03~ AFTER ~10RTHF01~ #1 #1 #1 ~IDENTIFIED~ #1 //Berywel's Cloak
	ADD_STORE_ITEM ~00RTHF04~ AFTER ~00BRAC12~ #1 #1 #1 ~IDENTIFIED~ #1 //School Cap
	ADD_STORE_ITEM ~USRTHF31~ AFTER ~00BELT05~ #1 #1 #1 ~IDENTIFIED~ #1 //Girdle of Beatification/HoF version
	REMOVE_STORE_ITEM ~00BELT05~ ~00RING75~ ~00RING78~

COPY_EXISTING ~11ragnib.sto~ ~override~ //Targos Temple of Tempus
	ADD_STORE_ITEM ~00RING77~ AFTER ~00RING80~ #1 #1 #1 ~IDENTIFIED~ #1 //Lesser Ring of Resistances
	REMOVE_STORE_ITEM ~00RING74~

COPY_EXISTING ~20arte.sto~ ~override~ //Shaengarne villager store
	ADD_STORE_ITEM ~11RTHF02~ #1 #1 #1 ~IDENTIFIED~ #1 //Lucky Knucky
	ADD_STORE_ITEM ~00RTHF12~ AFTER ~00MISC32~ #1 #1 #1 ~IDENTIFIED~ #1 //Hagnen's Foolishness

COPY_EXISTING ~20dereth.sto~ ~override~ //Dereth druid store
	ADD_STORE_ITEM ~SPPR502Z~ AFTER ~SPWI306Z~ #1 #1 #1 ~IDENTIFIED~ #3 //Cure Critical Wounds scroll
	ADD_STORE_ITEM ~SPPR403Z~ AFTER ~SPPR502Z~ #1 #1 #1 ~IDENTIFIED~ #1 //Freedom of Movement scroll
	ADD_STORE_ITEM ~SPPR422Z~ AFTER ~SPPR403Z~ #1 #1 #1 ~IDENTIFIED~ #2 //Thorn Spray scroll
	ADD_STORE_ITEM ~SPPR615Z~ AFTER ~SPPR422Z~ #1 #1 #1 ~IDENTIFIED~ #2 //Conjure Animals scroll
	ADD_STORE_ITEM ~SPPR613Z~ AFTER ~SPPR615Z~ #1 #1 #1 ~IDENTIFIED~ #1 //Whirlwind scroll
	ADD_STORE_ITEM ~SPPR729Z~ AFTER ~SPPR613Z~ #1 #1 #1 ~IDENTIFIED~ #1 //Aura of Vitality scroll

COPY_EXISTING ~40BDAWN.sto~ ~override~ //Beodaewn the Werewolf Man store
	ADD_STORE_ITEM ~USRTHF01~ AFTER ~00SPER99~ #1 #1 #1 ~IDENTIFIED~ #1 //Spear of Sorrows
	ADD_STORE_ITEM ~00RTHF47~ AFTER ~00BOOT02~ #1 #1 #1 ~IDENTIFIED~ #1 //Arcs of Disredain
	REMOVE_STORE_ITEM ~00AMUL12~ ~00SPER99~

COPY_EXISTING ~41ZACK1.sto~ ~override~ ~41ZACK2.sto~ ~override~ ~41ZACK3.sto~ ~override~ //Zack Boosenberry stores
	ADD_STORE_ITEM ~00RING78~ AFTER ~00RING20~ #1 #1 #1 ~IDENTIFIED~ #1 //Spirit Armor Ring
	ADD_STORE_ITEM ~00RING98~ AFTER ~00RING78~ #1 #1 #1 ~IDENTIFIED~ #1 //Chameleon Ring
	ADD_STORE_ITEM ~00WAND13~ AFTER ~00WAND06~ #50 #1 #1 ~IDENTIFIED~ #1 //Wand of Trap Detection
	REMOVE_STORE_ITEM ~00WAND06~

COPY_EXISTING ~50NYM2.sto~ ~override~ //Nym store
	ADD_STORE_ITEM ~00RTHF64~ AFTER ~00RING19~ #1 #1 #1 ~IDENTIFIED~ #1 //Delnar's Healing Sword

COPY_EXISTING ~00BASHS3.sto~ ~override~ //Avarine Decanter genie store
	WRITE_LONG 0x14 155 //Buying stuff from him costs less money (since he actually has some good stuff now), though his goods are still overpriced
	ADD_STORE_ITEM ~00ROBE16~ AFTER ~00ROBE15~ #1 #1 #1 ~IDENTIFIED~ #1 //Robe of Electrical Resistance
	ADD_STORE_ITEM ~50RTHF04~ AFTER ~00ROBE16~ #1 #1 #1 ~IDENTIFIED~ #1 //Milton Sixtoes armor
	ADD_STORE_ITEM ~00WAND42~ AFTER ~00WAND04~ #50 #1 #1 ~IDENTIFIED~ #1 //Wand of Cure Moderate Wounds
	ADD_STORE_ITEM ~00WAND43~ AFTER ~00WAND44~ #50 #1 #1 ~IDENTIFIED~ #1 //Wand of Spell Resistance
	ADD_STORE_ITEM ~USCLCK40~ AFTER ~00BELT03~ #1 #1 #1 ~IDENTIFIED~ #1 //Cloak of Protection +3
	ADD_STORE_ITEM ~USBRAC47~ AFTER ~00BOOT01~ #1 #1 #1 ~IDENTIFIED~ #1 //Bracers of Armor +5
	ADD_STORE_ITEM ~00RTHF73~ AFTER ~00BRAC10~ #1 #1 #1 ~IDENTIFIED~ #1 //Cleaver
	ADD_STORE_ITEM ~00RTHF58~ AFTER ~00RTHF73~ #1 #1 #1 ~IDENTIFIED~ #1 //Iron Mary crossbow
	ADD_STORE_ITEM ~00AROW07~ AFTER ~00POTN01~ #1 #1 #1 ~IDENTIFIED~ #1 //Arrow of Dispelling
	ADD_STORE_ITEM ~USBOLT52~ AFTER ~00AROW07~ #1 #1 #1 ~IDENTIFIED~ #12 //Bolt of Lightning
	REMOVE_STORE_ITEM ~00WAND24~

COPY_EXISTING ~50TAHVO.sto~ ~override~ //Nym store
	ADD_STORE_ITEM ~00RTHF51~ AFTER ~00BOWS03~ #1 #1 #1 ~IDENTIFIED~ #1 //Eye of the Hunter bow
	ADD_STORE_ITEM ~ZZG6CT~ AFTER ~00SPER98~ #1 #1 #1 ~IDENTIFIED~ #1 //Troll Killer club
	ADD_STORE_ITEM ~USRTHF03~ AFTER ~50HIDE06~ #1 #1 #1 ~IDENTIFIED~ #1 //Wandering Hunter Armor/HoF version
	ADD_STORE_ITEM ~USRTHF04~ AFTER ~50BOOT14~ #1 #1 #1 ~IDENTIFIED~ #1 //Wandering Hunter Boots/HoF version
	ADD_STORE_ITEM ~USRTHF05~ AFTER ~50CLCK17~ #1 #1 #1 ~IDENTIFIED~ #1 //Wandering Hunter Cloak/HoF version
	REMOVE_STORE_ITEM ~50HIDE06~ ~50BOOT14~ ~50CLCK17~

COPY_EXISTING ~50LIMHA.sto~ ~override~ //Limha store
	ADD_STORE_ITEM ~00RTHF88~ AFTER ~00AX1H82~ #1 #1 #1 ~IDENTIFIED~ #1 //Dragon's Sight
	ADD_STORE_ITEM ~00SWDL96~ AFTER ~00SWDL03~ #1 #1 #1 ~IDENTIFIED~ #1 //Longsword +1: Bloodletting
	ADD_STORE_ITEM ~00POTN22~ AFTER ~00SWDL96~ #1 #1 #1 ~IDENTIFIED~ #8 //Ogre Bile
	REMOVE_STORE_ITEM ~00AX1H82~ ~00SWDL03~

COPY_EXISTING ~51DRAGU.sto~ ~override~ ~51DRAGU2.sto~ ~override~ //Duergar engineer stores
	ADD_STORE_ITEM ~USBOLT48~ AFTER ~00BOLT04~ #20 #1 #1 ~IDENTIFIED~ #1 //Heavy Bolt +4

COPY_EXISTING ~52BERED.sto~ ~override~ //Beodaewn the Werewolf Man store
	REMOVE_STORE_ITEM ~52RTHF05~
	ADD_STORE_ITEM ~52RTHF05~ AFTER ~52RTHF04~ #6 #1 #1 ~IDENTIFIED~ #1 //How to be an Adventurer

COPY_EXISTING ~53HEGGR.sto~ ~override~ //Underdark weapon/armor store
	ADD_STORE_ITEM ~00SHLD85~ AFTER ~00SHLD16~ #1 #1 #1 ~IDENTIFIED~ #1 //Tower Shield of Spell Resistance +2
	REMOVE_STORE_ITEM ~00STAF93~

COPY_EXISTING ~53KADRES.sto~ ~override~ //Kadresh drow store
	ADD_STORE_ITEM ~00RTHF09~ #1 #3 #1 ~IDENTIFIED~ #1 //Spiritcaller
	ADD_STORE_ITEM ~00RING75~ AFTER ~00RING71~ #1 #1 #1 ~IDENTIFIED~ #1 //Chameleon Ring of Dexterity

COPY_EXISTING ~53MALAVO.sto~ ~override~ //Malavon store
	ADD_STORE_ITEM ~00AMUL15~ BEFORE ~00RING22~ #1 #1 #1 ~IDENTIFIED~ #1 //Amulet of Intellect
	ADD_STORE_ITEM ~00ROBE99~ BEFORE ~00STAF80~ #1 #1 #1 ~IDENTIFIED~ #1 //Robe of Enfusing
	ADD_STORE_ITEM ~00STAF93~ AFTER ~00STAF80~ #1 #1 #1 ~IDENTIFIED~ #1 //Staff of Magic Vulnerability +1
	ADD_STORE_ITEM ~USRING53~ AFTER ~00RING22~ #1 #1 #1 ~IDENTIFIED~ #1 //Onyx Ring of Teleportation

COPY_EXISTING ~53MYRVEK.sto~ ~override~ //Underdark magic store
	ADD_STORE_ITEM ~00BRAC04~ AFTER ~00BRAC03~ #1 #1 #1 ~IDENTIFIED~ #1 //Bracers of Armor +4
	ADD_STORE_ITEM ~USAMUL50~ AFTER ~00AMUL13~ #1 #1 #1 ~IDENTIFIED~ #1 //Amulet of Antimagic

COPY_EXISTING ~53WODE.sto~ ~override~ //Underdark ranged ammunition store
	ADD_STORE_ITEM ~USAROW47~ AFTER ~00AROW99~ #20 #1 #1 ~IDENTIFIED~ #1 //Arrows of Acid +4
	ADD_STORE_ITEM ~USAROW52~ AFTER ~USAROW47~ #1 #1 #1 ~IDENTIFIED~ #4 //Arrows of Detonation
	ADD_STORE_ITEM ~USBULL48~ AFTER ~00BULL99~ #20 #1 #1 ~IDENTIFIED~ #1 //Greater Vampiric Bullet +3

COPY_EXISTING ~60NATHAN.sto~ ~override~ //Kuldahar Nathaniel store
	ADD_STORE_ITEM ~USRTHF35~ AFTER ~00RTKT04~ #1 #1 #1 ~IDENTIFIED~ #1 //Woodland Cloak
	ADD_STORE_ITEM ~00RING74~ AFTER ~00RING68~ #1 #1 #1 ~IDENTIFIED~ #1 //Ring of Protection from Evil
	ADD_STORE_ITEM ~00STAF92~ AFTER ~USRTHF35~ #1 #1 #1 ~IDENTIFIED~ #1 //Staff of Banishing +2
	REMOVE_STORE_ITEM ~00RING21~

COPY_EXISTING ~60SHEEMI.sto~ ~override~ //Conlan store
	ADD_STORE_ITEM ~00RTKT02~ AFTER ~00RTHF58~ #1 #1 #1 ~IDENTIFIED~ #1 //Iron Arbalest
	ADD_STORE_ITEM ~USCHAN40~ AFTER ~00CHAN03~ #1 #1 #1 ~IDENTIFIED~ #1 //Chainmail +3
	ADD_STORE_ITEM ~USCHAN41~ AFTER ~USCHAN40~ #1 #1 #1 ~IDENTIFIED~ #1 //Splint Mail +3
	ADD_STORE_ITEM ~00SHLD89~ AFTER ~00SHLD98~ #1 #1 #1 ~IDENTIFIED~ #1 //Large Shield of Electrical Resistance +3
	ADD_STORE_ITEM ~00AX1H86~ AFTER ~00AX1H92~ #1 #1 #1 ~IDENTIFIED~ #1 //Mass-Slasher +5
	ADD_STORE_ITEM ~00AX2H99~ AFTER ~00AX2H89~ #1 #1 #1 ~IDENTIFIED~ #1 //Greataxe of Vampiric Burst +4
	ADD_STORE_ITEM ~00CLUB92~ AFTER ~00CLUB98~ #1 #1 #1 ~IDENTIFIED~ #1 //Club of Intoxication +4
	ADD_STORE_ITEM ~00MACE95~ AFTER ~00MACE97~ #1 #1 #1 ~IDENTIFIED~ #1 //Fiery Mace of Disruption +3
	ADD_STORE_ITEM ~00RTHF83~ AFTER ~00HAMM86~ #1 #1 #1 ~IDENTIFIED~ #1 //Protean Hammer
	ADD_STORE_ITEM ~00RTHF28~ AFTER ~00FLAL92~ #1 #1 #1 ~IDENTIFIED~ #1 //Shackles of Roa flail
	ADD_STORE_ITEM ~00STAF91~ AFTER ~00STAF97~ #1 #1 #1 ~IDENTIFIED~ #1 //Staff of Health +3
	ADD_STORE_ITEM ~00RTHF69~ AFTER ~00SPER97~ #1 #1 #1 ~IDENTIFIED~ #1 //Impaler
	ADD_STORE_ITEM ~00SWDT98~ AFTER ~00RTHF73~ #1 #1 #1 ~IDENTIFIED~ #1 //Greatsword of Flame +3
	ADD_STORE_ITEM ~00SWDL95~ AFTER ~00SWDL87~ #1 #1 #1 ~IDENTIFIED~ #1 //Longsword of Speed +2
	ADD_STORE_ITEM ~00RTHF65~ AFTER ~00SWDB87~ #1 #1 #1 ~IDENTIFIED~ #1 //Rage of Chaos
	ADD_STORE_ITEM ~00SWDC90~ AFTER ~00SWDC96~ #1 #1 #1 ~IDENTIFIED~ #1 //Scimitar: Blood Trails
	REMOVE_STORE_ITEM ~00RTHF26~ ~00RTHF54~ ~00RTHF58~ ~00RTHF73~ ~00HALB96~ ~00CLCK03~ ~00ROBE04~ ~00ROBE99~ ~00RING15~ ~00RING22~

COPY_EXISTING ~61RAKSHA.sto~ ~override~ //Rakshasa Nathaniel store
	ADD_STORE_ITEM ~62RTHF01~ #1 #1 #1 ~IDENTIFIED~ #1 //Dirty Bits armor
	ADD_STORE_ITEM ~00BWHX04~ BEFORE ~00BOLT98~ #1 #1 #1 ~IDENTIFIED~ #1 //Heavy Crossbow of Missile Weakness +2
	REMOVE_STORE_ITEM ~00RTHF47~ ~00RTHF55~ ~00WAND13~ ~00AROW07~

COPY_EXISTING ~63ERADRU.sto~ ~override~ //Xvim priest temple
	READ_LONG 0x10 ulgiash
	ulgiash |= 0x1
	WRITE_LONG 0x10 ulgiash //Can buy items from this store
	ADD_STORE_ITEM ~00HALB96~ #1 #1 #1 ~IDENTIFIED~ #1 //Massive Halberd of Hate +4

COPY_EXISTING ~63RIKI.sto~ ~override~ //Severed Hand thief store
	ADD_STORE_ITEM ~00RING81~ BEFORE ~00BOOT02~ #1 #1 #1 ~IDENTIFIED~ #1 //Tymora's Loop
	ADD_STORE_ITEM ~00AROW07~ AFTER ~00AROW94~ #1 #1 #1 ~IDENTIFIED~ #1 //Arrow of Dispelling
	ADD_STORE_ITEM ~USAROW52~ AFTER ~00AROW94~ #1 #1 #1 ~IDENTIFIED~ #9 //Arrows of Detonation
	ADD_STORE_ITEM ~USBOLT52~ AFTER ~00BOLT99~ #1 #1 #1 ~IDENTIFIED~ #9 //Bolts of Lightning
	ADD_STORE_ITEM ~USCLCK51~ AFTER ~00CLCK03~ #1 #1 #1 ~IDENTIFIED~ #9 //Improved Cloak of Displacement
	REMOVE_STORE_ITEM ~00CLCK03~


COPY_EXISTING ~ar3000.are~ ~override~ //Horde Fortress outside
	LPF REPLACE_AREA_ITEM_IWD2 INT_VAR charges1=2 single_match=1 STR_VAR old_item=~SPPR115Z~ new_item=~00POTN22~ END

COPY_EXISTING ~ar3101.are~ ~override~ //Guthma's cabin
	LPF REPLACE_AREA_ITEM_IWD2 INT_VAR charges1=1  charges2=1  charges3=1 single_match=1 STR_VAR old_item=~RT03_R~ new_item=~00RTHF59~ END

COPY_EXISTING ~ar5203.are~ ~override~ //Black Raven Tomb
	LPF REPLACE_AREA_ITEM_IWD2 INT_VAR single_match=1 STR_VAR old_item=~00RTHF28~ new_item=~00RTKT19~ END
	LPF REPLACE_AREA_ITEM_IWD2 INT_VAR single_match=1 STR_VAR old_item=~00BRAC04~ new_item=~00BOOT01~ END

COPY_EXISTING ~ar6051.are~ ~override~ //Yuan-ti lair
	LPF REPLACE_AREA_ITEM_IWD2 INT_VAR single_match=1 STR_VAR old_item=~50RTHF04~ new_item=~00RTHF61~ END
	LPF REPLACE_AREA_ITEM_IWD2 INT_VAR single_match=1 STR_VAR old_item=~00RTKT19~ new_item=~USRT16_V~ END

COPY_EXISTING ~ar6101.are~ ~override~ //Dragon's Eye first floor
	LPF REPLACE_AREA_ITEM_IWD2 INT_VAR charges1=1  charges2=1  charges3=1 single_match=1 STR_VAR old_item=~00RTKT02~ new_item=~RT13_R~ END
	LPF REPLACE_AREA_ITEM_IWD2 INT_VAR single_match=1 STR_VAR old_item=~00SWDT91~ new_item=~00SPER90~ END
	LPF REPLACE_AREA_ITEM_IWD2 INT_VAR charges1=4277 single_match=1 STR_VAR old_item=~00BRAC03~ new_item=~MISC07~ END
	LPF REPLACE_AREA_ITEM_IWD2 INT_VAR charges1=652 single_match=1 STR_VAR old_item=~00HAMM04~ new_item=~MISC07~ END
	LPF REPLACE_AREA_ITEM_IWD2 INT_VAR charges1=1 single_match=1 STR_VAR old_item=~00SWDS85~ new_item=~00POTN80~ END
	LPF REPLACE_AREA_ITEM_IWD2 INT_VAR charges1=1  charges2=1  charges3=1 single_match=1 STR_VAR old_item=~00SWDB91~ new_item=~RT13_R~ END

COPY_EXISTING ~ar6102.are~ ~override~ //Dragon's Eye second floor
	LPF REPLACE_AREA_ITEM_IWD2 INT_VAR charges1=1  charges2=1  charges3=1 single_match=1 STR_VAR old_item=~00RTHF59~ new_item=~00SLNG97~ END

COPY_EXISTING ~ar6103.are~ ~override~ //Dragon's Eye third floor
	LPF REPLACE_AREA_ITEM_IWD2 INT_VAR charges1=1  charges2=1  charges3=1 single_match=1 STR_VAR old_item=~00RING18~ new_item=~USRT17_V~ END

COPY_EXISTING ~ar6300.are~ ~override~ //Severed Hand entrance
	LPF REPLACE_AREA_ITEM_IWD2 INT_VAR charges1=50 single_match=1 STR_VAR old_item=~00RTHF69~ new_item=~00WAND34~ END

COPY_EXISTING ~ar6301.are~ ~override~ //Severed Hand first floor
	LPF REPLACE_AREA_ITEM_IWD2 INT_VAR charges1=1 single_match=1 STR_VAR old_item=~00RTHF09~ new_item=~00POTN95~ END
	LPF REPLACE_AREA_ITEM_IWD2 INT_VAR charges1=2389 single_match=1 STR_VAR old_item=~00RTHF64~ new_item=~MISC07~ END
	LPF REPLACE_AREA_ITEM_IWD2 INT_VAR charges1=1 single_match=1 STR_VAR old_item=~00RTHF65~ new_item=~USALBEHO~ END

COPY_EXISTING ~ar6304.are~ ~override~ //Severed Hand fourth floor
	LPF REPLACE_AREA_ITEM_IWD2 INT_VAR charges1=1 single_match=1 STR_VAR old_item=~00RTHF40~ new_item=~00POTN68~ END


COPY_EXISTING ~11jemel.cre~ ~override~ //Gallaway Trading Post worker
	LPF IWD2_ADD_CRE_ITEM INT_VAR cq1=0  cq2=0  cq3=0 STR_VAR item=~~ slot=~qitem1~ END
//	LPF IWD2_REMOVE_CRE_ITEM STR_VAR item=~11RTHF02~ END

COPY_EXISTING ~60hiephe.cre~ ~override~ ~60hiephh.cre~ ~override~ //Hiepherus
	LPF IWD2_ADD_CRE_ITEM INT_VAR cq1=1  cq2=1  cq3=1 STR_VAR item=~00RTHF46~ slot=~cloak~ END

COPY_EXISTING ~62mdarf.cre~ ~override~ //Lich in Fields of Slaughter
	LPF IWD2_ADD_CRE_ITEM INT_VAR cq1=1  cq2=1  cq3=1 STR_VAR item=~USRT18_V~ slot=~inv6~ END

COPY_EXISTING ~62saabl1.cre~ ~override~ ~62saabl2.cre~ ~override~ //Saablic Tan
	LPF IWD2_ADD_CRE_ITEM INT_VAR cq1=0  cq2=0  cq3=0 STR_VAR item=~~ slot=~cloak~ END
//	LPF IWD2_REMOVE_CRE_ITEM STR_VAR item=~00RTHF46~ END

COPY_EXISTING ~63grdcom.cre~ ~override~ //Guard Commander at Severed Hand Entrance
	LPF IWD2_ADD_CRE_ITEM INT_VAR cq1=1  cq2=1  cq3=1 STR_VAR item=~00RTHF40~ slot=~helmet~ END

COPY_EXISTING ~65iytxm.cre~ ~override~ //Iyachtu Xvim
	LPF IWD2_ADD_CRE_ITEM INT_VAR cq1=1  cq2=1  cq3=1 STR_VAR item=~USRT19_V~ slot=~inv7~ END

COPY_EXISTING ~67trmal.cre~ ~override~ //Elite on Severed Hand rooftop
	LPF IWD2_ADD_CRE_ITEM INT_VAR cq1=0  cq2=0  cq3=0 STR_VAR item=~~ slot=~armor~ END
//	LPF IWD2_REMOVE_CRE_ITEM STR_VAR item=~00RTHF04~ END


COPY_EXISTING ~20newder.dlg~ ~override~ //Dereth Springsong dialogue
	REPLACE_TEXTUALLY CASE_INSENSITIVE ~00SWDC99~ ~00RTHF26~

COPY_EXISTING ~50nym.dlg~ ~override~ //Nym dialogue
	DECOMPILE_DLG_TO_D
	REPLACE_TEXTUALLY CASE_INSENSITIVE ~StartStore(\"50Nym\"~ ~StartStore("50Nym2"~
	COMPILE_D_TO_DLG
	LPF CONVERT_DLG_TO_IWD2_FORMAT END

COPY_EXISTING ~00bahsh.dlg~ ~override~ //Avarine Decanter genie dialogue
	REPLACE_TEXTUALLY CASE_INSENSITIVE ~StartStore(\"00Bashs1\"~ ~StartStore("00Bashs3"~
	REPLACE_TEXTUALLY CASE_INSENSITIVE ~StartStore(\"00Bashs2\"~ ~StartStore("00Bashs3"~

COPY_EXISTING ~60jerms2.dlg~ ~override~ //Jermsy dialogue
	REPLACE_TEXTUALLY CASE_INSENSITIVE ~00RTHF51~ ~00RTHF54~